/**
 * Plain CSS Custom Properties Transformer
 *
 * Converts DTCG token tree to CSS custom properties without Tailwind dependencies.
 */

import type { DTCGRoot, TransformOptions } from '@syncupsuite/tokens';
import { flattenTokens, sanitizeCssComment } from '@syncupsuite/tokens';
import type { DTCGTokenGroup } from '@syncupsuite/tokens';
import { formatProperty } from './format';

/**
 * Transform a DTCG token tree into plain CSS custom properties.
 */
export function transformToCSS(
  tokens: DTCGRoot,
  options: TransformOptions = {},
): string {
  const {
    darkMode = true,
    darkModeStrategy = 'class',
    includeComments = true,
    prefix = '',
  } = options;

  const sections: string[] = [];

  if (includeComments) {
    const name = sanitizeCssComment(tokens.$name || 'Theme');
    sections.push(`/* ═══════════════════════════════════════════════════════════════`);
    sections.push(` * ${name} — Design Tokens`);
    sections.push(` * Generated by @syncupsuite/transformers`);
    sections.push(` *`);
    sections.push(` * CONSUMER API — Use these semantic tokens in your styles:`);
    sections.push(` *`);
    sections.push(` * Backgrounds:  var(--background-canvas | surface | muted)`);
    sections.push(` * Text:         var(--text-primary | secondary | muted | inverse)`);
    sections.push(` * Interactive:  var(--interactive-primary | primary-hover | primary-active)`);
    sections.push(` * Borders:      var(--border-default | strong)`);
    sections.push(` * Status:       var(--status-error | success | warning | info)`);
    sections.push(` * Focus:        var(--focus-ring)`);
    sections.push(` *`);
    sections.push(` * Dark mode:    Add [data-theme="dark"] to a parent element.`);
    sections.push(` * Primitives:   --primitive-color-*, --primitive-spacing-*, etc.`);
    sections.push(` * ═══════════════════════════════════════════════════════════════ */`);
    sections.push('');
  }

  // Primitive tokens in :root
  if (tokens.primitive) {
    sections.push(':root {');

    // Colors
    if (tokens.primitive.color) {
      if (includeComments) sections.push('  /* --- Primitive Colors --- */');
      const colorTokens = flattenTokens(tokens.primitive.color as DTCGTokenGroup);
      for (const [path, token] of colorTokens) {
        const fullPath = ['primitive', 'color', ...path];
        sections.push(formatProperty(fullPath, token, prefix, includeComments));
      }
      sections.push('');
    }

    // Typography
    if (tokens.primitive.typography) {
      if (includeComments) sections.push('  /* --- Typography --- */');
      const typoTokens = flattenTokens(tokens.primitive.typography as DTCGTokenGroup);
      for (const [path, token] of typoTokens) {
        const fullPath = ['primitive', 'typography', ...path];
        sections.push(formatProperty(fullPath, token, prefix, includeComments));
      }
      sections.push('');
    }

    // Spacing
    if (tokens.primitive.spacing) {
      if (includeComments) sections.push('  /* --- Spacing --- */');
      const spacingTokens = flattenTokens(tokens.primitive.spacing as DTCGTokenGroup);
      for (const [path, token] of spacingTokens) {
        const fullPath = ['primitive', 'spacing', ...path];
        sections.push(formatProperty(fullPath, token, prefix, includeComments));
      }
      sections.push('');
    }

    // Radius
    if (tokens.primitive.radius) {
      if (includeComments) sections.push('  /* --- Border Radius --- */');
      const radiusTokens = flattenTokens(tokens.primitive.radius as DTCGTokenGroup);
      for (const [path, token] of radiusTokens) {
        const fullPath = ['primitive', 'radius', ...path];
        sections.push(formatProperty(fullPath, token, prefix, includeComments));
      }
    }

    // Semantic light tokens also in :root
    if (tokens.semantic?.light) {
      sections.push('');
      if (includeComments) sections.push('  /* --- Semantic Tokens (Light) --- */');
      const lightTokens = flattenTokens(tokens.semantic.light);
      for (const [path, token] of lightTokens) {
        sections.push(formatProperty(path, token, prefix, includeComments));
      }
    }

    sections.push('}');
    sections.push('');
  }

  // Dark mode
  if (darkMode && tokens.semantic?.dark) {
    const darkTokens = flattenTokens(tokens.semantic.dark);
    if (darkTokens.length > 0) {
      if (darkModeStrategy === 'media') {
        sections.push('@media (prefers-color-scheme: dark) {');
        sections.push('  :root {');
        for (const [path, token] of darkTokens) {
          sections.push(formatProperty(path, token, prefix, includeComments, '    '));
        }
        sections.push('  }');
        sections.push('}');
      } else {
        sections.push('[data-theme="dark"] {');
        for (const [path, token] of darkTokens) {
          sections.push(formatProperty(path, token, prefix, includeComments));
        }
        sections.push('}');
      }
      sections.push('');
    }
  }

  return sections.join('\n');
}
