// Auto-generated by scripts/generate-themes.ts — do not edit
export const css = `/* ═══════════════════════════════════════════════════════════════
 * swiss-international-style — Design Tokens
 * Generated by @syncupsuite/transformers
 *
 * CONSUMER API — Use these semantic tokens in your styles:
 *
 * Backgrounds:  var(--background-canvas | surface | muted)
 * Text:         var(--text-primary | secondary | muted | inverse)
 * Interactive:  var(--interactive-primary | primary-hover | primary-active)
 * Borders:      var(--border-default | strong)
 * Status:       var(--status-error | success | warning | info)
 * Focus:        var(--focus-ring)
 *
 * Dark mode:    Add [data-theme="dark"] to a parent element.
 * Primitives:   --primitive-color-*, --primitive-spacing-*, etc.
 * ═══════════════════════════════════════════════════════════════ */

:root {
  /* --- Primitive Colors --- */
  /* Schwarz 50 */
  --primitive-color-schwarz-50: #F5F5F5;
  /* Schwarz 100 */
  --primitive-color-schwarz-100: #C1C1C1;
  /* Schwarz 200 */
  --primitive-color-schwarz-200: #909090;
  /* Schwarz 300 */
  --primitive-color-schwarz-300: #626262;
  /* Schwarz 400 */
  --primitive-color-schwarz-400: #373737;
  /* Schwarz 500 */
  --primitive-color-schwarz-500: #111111;
  /* Schwarz 600 */
  --primitive-color-schwarz-600: #0E0E0E;
  /* Schwarz 700 */
  --primitive-color-schwarz-700: #0B0B0B;
  /* Schwarz 800 */
  --primitive-color-schwarz-800: #080808;
  /* Schwarz 900 */
  --primitive-color-schwarz-900: #060606;
  /* Weiss 50 */
  --primitive-color-weiss-50: #F5F5F5;
  /* Weiss 100 */
  --primitive-color-weiss-100: #F6F6F6;
  /* Weiss 200 */
  --primitive-color-weiss-200: #F7F7F7;
  /* Weiss 300 */
  --primitive-color-weiss-300: #F8F8F8;
  /* Weiss 400 */
  --primitive-color-weiss-400: #F9F9F9;
  /* Weiss 500 */
  --primitive-color-weiss-500: #FAFAFA;
  /* Weiss 600 */
  --primitive-color-weiss-600: #B4B4B4;
  /* Weiss 700 */
  --primitive-color-weiss-700: #727272;
  /* Weiss 800 */
  --primitive-color-weiss-800: #373737;
  /* Weiss 900 */
  --primitive-color-weiss-900: #060606;
  /* Rot (Signal Red) 50 */
  --primitive-color-rot-signal-red-50: #FFE8E1;
  /* Rot (Signal Red) 100 */
  --primitive-color-rot-signal-red-100: #FFC8BE;
  /* Rot (Signal Red) 200 */
  --primitive-color-rot-signal-red-200: #FFA79B;
  /* Rot (Signal Red) 300 */
  --primitive-color-rot-signal-red-300: #FF8578;
  /* Rot (Signal Red) 400 */
  --primitive-color-rot-signal-red-400: #F56055;
  /* Rot (Signal Red) 500 */
  --primitive-color-rot-signal-red-500: #E8322E;
  /* Rot (Signal Red) 600 */
  --primitive-color-rot-signal-red-600: #B40510;
  /* Rot (Signal Red) 700 */
  --primitive-color-rot-signal-red-700: #820000;
  /* Rot (Signal Red) 800 */
  --primitive-color-rot-signal-red-800: #530000;
  /* Rot (Signal Red) 900 */
  --primitive-color-rot-signal-red-900: #260000;
  /* Mittelgrau 50 */
  --primitive-color-mittelgrau-50: #F5F5F5;
  /* Mittelgrau 100 */
  --primitive-color-mittelgrau-100: #D8D8D8;
  /* Mittelgrau 200 */
  --primitive-color-mittelgrau-200: #BDBDBD;
  /* Mittelgrau 300 */
  --primitive-color-mittelgrau-300: #A2A2A2;
  /* Mittelgrau 400 */
  --primitive-color-mittelgrau-400: #878787;
  /* Mittelgrau 500 */
  --primitive-color-mittelgrau-500: #6E6E6E;
  /* Mittelgrau 600 */
  --primitive-color-mittelgrau-600: #515151;
  /* Mittelgrau 700 */
  --primitive-color-mittelgrau-700: #353535;
  /* Mittelgrau 800 */
  --primitive-color-mittelgrau-800: #1C1C1C;
  /* Mittelgrau 900 */
  --primitive-color-mittelgrau-900: #060606;
  /* Hellgrau 50 */
  --primitive-color-hellgrau-50: #F5F5F5;
  /* Hellgrau 100 */
  --primitive-color-hellgrau-100: #EEEEEE;
  /* Hellgrau 200 */
  --primitive-color-hellgrau-200: #E8E8E8;
  /* Hellgrau 300 */
  --primitive-color-hellgrau-300: #E1E1E1;
  /* Hellgrau 400 */
  --primitive-color-hellgrau-400: #DBDBDB;
  /* Hellgrau 500 */
  --primitive-color-hellgrau-500: #D4D4D4;
  /* Hellgrau 600 */
  --primitive-color-hellgrau-600: #999999;
  /* Hellgrau 700 */
  --primitive-color-hellgrau-700: #626262;
  /* Hellgrau 800 */
  --primitive-color-hellgrau-800: #303030;
  /* Hellgrau 900 */
  --primitive-color-hellgrau-900: #060606;
  /* Dunkelblau 50 */
  --primitive-color-dunkelblau-50: #EDF6FF;
  /* Dunkelblau 100 */
  --primitive-color-dunkelblau-100: #BFCEDE;
  /* Dunkelblau 200 */
  --primitive-color-dunkelblau-200: #93A6BD;
  /* Dunkelblau 300 */
  --primitive-color-dunkelblau-300: #69819C;
  /* Dunkelblau 400 */
  --primitive-color-dunkelblau-400: #415C7B;
  /* Dunkelblau 500 */
  --primitive-color-dunkelblau-500: #1A3A5C;
  /* Dunkelblau 600 */
  --primitive-color-dunkelblau-600: #0F2C49;
  /* Dunkelblau 700 */
  --primitive-color-dunkelblau-700: #061E37;
  /* Dunkelblau 800 */
  --primitive-color-dunkelblau-800: #011125;
  /* Dunkelblau 900 */
  --primitive-color-dunkelblau-900: #000615;
  /* Neutral 50 */
  --primitive-color-neutral-50: #FBF8F1;
  /* Neutral 100 */
  --primitive-color-neutral-100: #F1EEE7;
  /* Neutral 200 */
  --primitive-color-neutral-200: #E0DED7;
  /* Neutral 300 */
  --primitive-color-neutral-300: #C6C4BD;
  /* Neutral 400 */
  --primitive-color-neutral-400: #9B9891;
  /* Neutral 500 */
  --primitive-color-neutral-500: #716E68;
  /* Neutral 600 */
  --primitive-color-neutral-600: #4F4D47;
  /* Neutral 700 */
  --primitive-color-neutral-700: #35332D;
  /* Neutral 800 */
  --primitive-color-neutral-800: #1C1A15;
  /* Neutral 900 */
  --primitive-color-neutral-900: #090704;
  /* Accent 50 */
  --primitive-color-accent-50: #FAF3F3;
  /* Accent 100 */
  --primitive-color-accent-100: #D5CBCB;
  /* Accent 200 */
  --primitive-color-accent-200: #B1A4A4;
  /* Accent 300 */
  --primitive-color-accent-300: #8F7F7F;
  /* Accent 400 */
  --primitive-color-accent-400: #6E5B5B;
  /* Accent 500 */
  --primitive-color-accent-500: #4E3A3A;
  /* Accent 600 */
  --primitive-color-accent-600: #3C2B2B;
  /* Accent 700 */
  --primitive-color-accent-700: #2B1C1C;
  /* Accent 800 */
  --primitive-color-accent-800: #1A0F0F;
  /* Accent 900 */
  --primitive-color-accent-900: #0B0404;

  /* --- Typography --- */
  /* Heading font family */
  --primitive-typography-family-heading: "Inter", "Helvetica Neue", "Arial", sans-serif;
  /* Body font family */
  --primitive-typography-family-body: "Inter", "Helvetica Neue", "Arial", sans-serif;
  /* Monospace font family */
  --primitive-typography-family-mono: "JetBrains Mono", "SF Mono", monospace;
  /* Font size xs */
  --primitive-typography-size-xs: 0.75rem;
  /* Font size sm */
  --primitive-typography-size-sm: 0.875rem;
  /* Font size base */
  --primitive-typography-size-base: 1rem;
  /* Font size lg */
  --primitive-typography-size-lg: 1.125rem;
  /* Font size xl */
  --primitive-typography-size-xl: 1.25rem;
  /* Font size 2xl */
  --primitive-typography-size-2xl: 1.5rem;
  /* Font size 3xl */
  --primitive-typography-size-3xl: 1.875rem;
  /* Font size 4xl */
  --primitive-typography-size-4xl: 2.25rem;
  /* Font weight normal */
  --primitive-typography-weight-normal: 400;
  /* Font weight medium */
  --primitive-typography-weight-medium: 500;
  /* Font weight semibold */
  --primitive-typography-weight-semibold: 600;
  /* Font weight bold */
  --primitive-typography-weight-bold: 700;
  /* Line height tight */
  --primitive-typography-lineHeight-tight: 1.25;
  /* Line height normal */
  --primitive-typography-lineHeight-normal: 1.5;
  /* Line height relaxed */
  --primitive-typography-lineHeight-relaxed: 1.75;

  /* --- Spacing --- */
  /* Spacing 0 (0px) */
  --primitive-spacing-0: 0px;
  /* Spacing 1 (4px) */
  --primitive-spacing-1: 4px;
  /* Spacing 2 (8px) */
  --primitive-spacing-2: 8px;
  /* Spacing 3 (12px) */
  --primitive-spacing-3: 12px;
  /* Spacing 4 (16px) */
  --primitive-spacing-4: 16px;
  /* Spacing 5 (20px) */
  --primitive-spacing-5: 20px;
  /* Spacing 6 (24px) */
  --primitive-spacing-6: 24px;
  /* Spacing 8 (32px) */
  --primitive-spacing-8: 32px;
  /* Spacing 10 (40px) */
  --primitive-spacing-10: 40px;
  /* Spacing 12 (48px) */
  --primitive-spacing-12: 48px;
  /* Spacing 16 (64px) */
  --primitive-spacing-16: 64px;
  /* Spacing 20 (80px) */
  --primitive-spacing-20: 80px;
  /* Spacing 0.5 (2px) */
  --primitive-spacing-0-5: 2px;
  /* Spacing 1.5 (6px) */
  --primitive-spacing-1-5: 6px;

  /* --- Border Radius --- */
  /* Border radius none */
  --primitive-radius-none: 0px;
  /* Border radius sm */
  --primitive-radius-sm: 0px;
  /* Border radius md */
  --primitive-radius-md: 0px;
  /* Border radius lg */
  --primitive-radius-lg: 0px;
  /* Border radius xl */
  --primitive-radius-xl: 0px;
  /* Border radius full */
  --primitive-radius-full: 9999px;

  /* --- Semantic Tokens (Light) --- */
  /* Page background */
  --background-canvas: var(--primitive-color-neutral-50);
  /* Card/surface background */
  --background-surface: #FFFFFF;
  /* Muted background */
  --background-muted: var(--primitive-color-neutral-100);
  /* Primary text */
  --text-primary: var(--primitive-color-neutral-900);
  /* Secondary text */
  --text-secondary: var(--primitive-color-neutral-600);
  /* Muted/disabled text */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on dark backgrounds */
  --text-inverse: var(--primitive-color-neutral-50);
  /* Primary interactive (buttons, links) */
  --interactive-primary: var(--primitive-color-schwarz-500);
  /* Primary interactive hover */
  --interactive-primary-hover: var(--primitive-color-schwarz-600);
  /* Primary interactive active */
  --interactive-primary-active: var(--primitive-color-schwarz-700);
  /* Default border */
  --border-default: var(--primitive-color-neutral-200);
  /* Strong border */
  --border-strong: var(--primitive-color-neutral-400);
  /* Error — WCAG-compliant red */
  --status-error: #DC2626;
  /* Success — WCAG-compliant green */
  --status-success: #16A34A;
  /* Warning — WCAG AA amber (4.5:1+ on white) */
  --status-warning: #A16207;
  /* Info status */
  --status-info: var(--primitive-color-schwarz-500);
  /* Focus ring color */
  --focus-ring: var(--primitive-color-schwarz-500);
  /* Keyboard focus indicator */
  --accessibility-focus-visible: var(--primitive-color-schwarz-500);
}

[data-theme="dark"] {
  /* Page background — dark */
  --background-canvas: var(--primitive-color-neutral-900);
  /* Card/surface — dark */
  --background-surface: var(--primitive-color-neutral-800);
  /* Muted background — dark */
  --background-muted: var(--primitive-color-neutral-700);
  /* Primary text — dark */
  --text-primary: var(--primitive-color-neutral-50);
  /* Secondary text — dark */
  --text-secondary: var(--primitive-color-neutral-300);
  /* Muted text — dark */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on light backgrounds — dark */
  --text-inverse: var(--primitive-color-neutral-900);
  /* Primary interactive — dark */
  --interactive-primary: var(--primitive-color-rot-signal-red-400);
  /* Primary hover — dark */
  --interactive-primary-hover: var(--primitive-color-rot-signal-red-300);
  /* Primary active — dark */
  --interactive-primary-active: var(--primitive-color-rot-signal-red-200);
  /* Default border — dark */
  --border-default: var(--primitive-color-neutral-700);
  /* Strong border — dark */
  --border-strong: var(--primitive-color-neutral-500);
  /* Error — WCAG-compliant red (dark) */
  --status-error: #EF4444;
  /* Success — WCAG-compliant green (dark) */
  --status-success: #22C55E;
  /* Warning — WCAG-compliant amber (dark) */
  --status-warning: #EAB308;
  /* Info — dark */
  --status-info: var(--primitive-color-rot-signal-red-400);
  /* Focus ring — dark */
  --focus-ring: var(--primitive-color-rot-signal-red-400);
  /* Keyboard focus — dark */
  --accessibility-focus-visible: var(--primitive-color-rot-signal-red-400);
}
`;
export const tailwindCss = `@import "tailwindcss";

@theme {
  /* --- Colors --- */
  /* Schwarz 50 */
  --color-schwarz-50: #F5F5F5;
  /* Schwarz 100 */
  --color-schwarz-100: #C1C1C1;
  /* Schwarz 200 */
  --color-schwarz-200: #909090;
  /* Schwarz 300 */
  --color-schwarz-300: #626262;
  /* Schwarz 400 */
  --color-schwarz-400: #373737;
  /* Schwarz 500 */
  --color-schwarz-500: #111111;
  /* Schwarz 600 */
  --color-schwarz-600: #0E0E0E;
  /* Schwarz 700 */
  --color-schwarz-700: #0B0B0B;
  /* Schwarz 800 */
  --color-schwarz-800: #080808;
  /* Schwarz 900 */
  --color-schwarz-900: #060606;
  /* Weiss 50 */
  --color-weiss-50: #F5F5F5;
  /* Weiss 100 */
  --color-weiss-100: #F6F6F6;
  /* Weiss 200 */
  --color-weiss-200: #F7F7F7;
  /* Weiss 300 */
  --color-weiss-300: #F8F8F8;
  /* Weiss 400 */
  --color-weiss-400: #F9F9F9;
  /* Weiss 500 */
  --color-weiss-500: #FAFAFA;
  /* Weiss 600 */
  --color-weiss-600: #B4B4B4;
  /* Weiss 700 */
  --color-weiss-700: #727272;
  /* Weiss 800 */
  --color-weiss-800: #373737;
  /* Weiss 900 */
  --color-weiss-900: #060606;
  /* Rot (Signal Red) 50 */
  --color-rot-signal-red-50: #FFE8E1;
  /* Rot (Signal Red) 100 */
  --color-rot-signal-red-100: #FFC8BE;
  /* Rot (Signal Red) 200 */
  --color-rot-signal-red-200: #FFA79B;
  /* Rot (Signal Red) 300 */
  --color-rot-signal-red-300: #FF8578;
  /* Rot (Signal Red) 400 */
  --color-rot-signal-red-400: #F56055;
  /* Rot (Signal Red) 500 */
  --color-rot-signal-red-500: #E8322E;
  /* Rot (Signal Red) 600 */
  --color-rot-signal-red-600: #B40510;
  /* Rot (Signal Red) 700 */
  --color-rot-signal-red-700: #820000;
  /* Rot (Signal Red) 800 */
  --color-rot-signal-red-800: #530000;
  /* Rot (Signal Red) 900 */
  --color-rot-signal-red-900: #260000;
  /* Mittelgrau 50 */
  --color-mittelgrau-50: #F5F5F5;
  /* Mittelgrau 100 */
  --color-mittelgrau-100: #D8D8D8;
  /* Mittelgrau 200 */
  --color-mittelgrau-200: #BDBDBD;
  /* Mittelgrau 300 */
  --color-mittelgrau-300: #A2A2A2;
  /* Mittelgrau 400 */
  --color-mittelgrau-400: #878787;
  /* Mittelgrau 500 */
  --color-mittelgrau-500: #6E6E6E;
  /* Mittelgrau 600 */
  --color-mittelgrau-600: #515151;
  /* Mittelgrau 700 */
  --color-mittelgrau-700: #353535;
  /* Mittelgrau 800 */
  --color-mittelgrau-800: #1C1C1C;
  /* Mittelgrau 900 */
  --color-mittelgrau-900: #060606;
  /* Hellgrau 50 */
  --color-hellgrau-50: #F5F5F5;
  /* Hellgrau 100 */
  --color-hellgrau-100: #EEEEEE;
  /* Hellgrau 200 */
  --color-hellgrau-200: #E8E8E8;
  /* Hellgrau 300 */
  --color-hellgrau-300: #E1E1E1;
  /* Hellgrau 400 */
  --color-hellgrau-400: #DBDBDB;
  /* Hellgrau 500 */
  --color-hellgrau-500: #D4D4D4;
  /* Hellgrau 600 */
  --color-hellgrau-600: #999999;
  /* Hellgrau 700 */
  --color-hellgrau-700: #626262;
  /* Hellgrau 800 */
  --color-hellgrau-800: #303030;
  /* Hellgrau 900 */
  --color-hellgrau-900: #060606;
  /* Dunkelblau 50 */
  --color-dunkelblau-50: #EDF6FF;
  /* Dunkelblau 100 */
  --color-dunkelblau-100: #BFCEDE;
  /* Dunkelblau 200 */
  --color-dunkelblau-200: #93A6BD;
  /* Dunkelblau 300 */
  --color-dunkelblau-300: #69819C;
  /* Dunkelblau 400 */
  --color-dunkelblau-400: #415C7B;
  /* Dunkelblau 500 */
  --color-dunkelblau-500: #1A3A5C;
  /* Dunkelblau 600 */
  --color-dunkelblau-600: #0F2C49;
  /* Dunkelblau 700 */
  --color-dunkelblau-700: #061E37;
  /* Dunkelblau 800 */
  --color-dunkelblau-800: #011125;
  /* Dunkelblau 900 */
  --color-dunkelblau-900: #000615;
  /* Neutral 50 */
  --color-neutral-50: #FBF8F1;
  /* Neutral 100 */
  --color-neutral-100: #F1EEE7;
  /* Neutral 200 */
  --color-neutral-200: #E0DED7;
  /* Neutral 300 */
  --color-neutral-300: #C6C4BD;
  /* Neutral 400 */
  --color-neutral-400: #9B9891;
  /* Neutral 500 */
  --color-neutral-500: #716E68;
  /* Neutral 600 */
  --color-neutral-600: #4F4D47;
  /* Neutral 700 */
  --color-neutral-700: #35332D;
  /* Neutral 800 */
  --color-neutral-800: #1C1A15;
  /* Neutral 900 */
  --color-neutral-900: #090704;
  /* Accent 50 */
  --color-accent-50: #FAF3F3;
  /* Accent 100 */
  --color-accent-100: #D5CBCB;
  /* Accent 200 */
  --color-accent-200: #B1A4A4;
  /* Accent 300 */
  --color-accent-300: #8F7F7F;
  /* Accent 400 */
  --color-accent-400: #6E5B5B;
  /* Accent 500 */
  --color-accent-500: #4E3A3A;
  /* Accent 600 */
  --color-accent-600: #3C2B2B;
  /* Accent 700 */
  --color-accent-700: #2B1C1C;
  /* Accent 800 */
  --color-accent-800: #1A0F0F;
  /* Accent 900 */
  --color-accent-900: #0B0404;

  /* --- Spacing (8px grid) --- */
  /* Spacing 0 (0px) */
  --spacing-0: 0px;
  /* Spacing 1 (4px) */
  --spacing-1: 4px;
  /* Spacing 2 (8px) */
  --spacing-2: 8px;
  /* Spacing 3 (12px) */
  --spacing-3: 12px;
  /* Spacing 4 (16px) */
  --spacing-4: 16px;
  /* Spacing 5 (20px) */
  --spacing-5: 20px;
  /* Spacing 6 (24px) */
  --spacing-6: 24px;
  /* Spacing 8 (32px) */
  --spacing-8: 32px;
  /* Spacing 10 (40px) */
  --spacing-10: 40px;
  /* Spacing 12 (48px) */
  --spacing-12: 48px;
  /* Spacing 16 (64px) */
  --spacing-16: 64px;
  /* Spacing 20 (80px) */
  --spacing-20: 80px;
  /* Spacing 0.5 (2px) */
  --spacing-0-5: 2px;
  /* Spacing 1.5 (6px) */
  --spacing-1-5: 6px;

  /* --- Font Families --- */
  /* Heading font family */
  --font-heading: "Inter", "Helvetica Neue", "Arial", sans-serif;
  /* Body font family */
  --font-body: "Inter", "Helvetica Neue", "Arial", sans-serif;
  /* Monospace font family */
  --font-mono: "JetBrains Mono", "SF Mono", monospace;

  /* --- Font Sizes --- */
  /* Font size xs */
  --text-xs: 0.75rem;
  /* Font size sm */
  --text-sm: 0.875rem;
  /* Font size base */
  --text-base: 1rem;
  /* Font size lg */
  --text-lg: 1.125rem;
  /* Font size xl */
  --text-xl: 1.25rem;
  /* Font size 2xl */
  --text-2xl: 1.5rem;
  /* Font size 3xl */
  --text-3xl: 1.875rem;
  /* Font size 4xl */
  --text-4xl: 2.25rem;

  /* --- Border Radius --- */
  /* Border radius none */
  --radius-none: 0px;
  /* Border radius sm */
  --radius-sm: 0px;
  /* Border radius md */
  --radius-md: 0px;
  /* Border radius lg */
  --radius-lg: 0px;
  /* Border radius xl */
  --radius-xl: 0px;
  /* Border radius full */
  --radius-full: 9999px;

}

/* === Semantic Color API — theme-aware Tailwind utilities === */
@theme {
  --color-canvas: var(--background-canvas);
  --color-surface: var(--background-surface);
  --color-muted: var(--background-muted);
  --color-foreground: var(--text-primary);
  --color-foreground-secondary: var(--text-secondary);
  --color-foreground-muted: var(--text-muted);
  --color-foreground-inverse: var(--text-inverse);
  --color-primary: var(--interactive-primary);
  --color-primary-hover: var(--interactive-primary-hover);
  --color-primary-active: var(--interactive-primary-active);
  --color-border: var(--border-default);
  --color-border-strong: var(--border-strong);
  --color-error: var(--status-error);
  --color-success: var(--status-success);
  --color-warning: var(--status-warning);
  --color-info: var(--status-info);
  --color-ring: var(--focus-ring);
  --color-focus-visible: var(--accessibility-focus-visible);
}

/* Primitive aliases + light mode semantic tokens */
:root {
  /* --primitive-color-* aliases → @theme --color-* (for semantic var() resolution) */
  --primitive-color-schwarz-50: var(--color-schwarz-50);
  --primitive-color-schwarz-100: var(--color-schwarz-100);
  --primitive-color-schwarz-200: var(--color-schwarz-200);
  --primitive-color-schwarz-300: var(--color-schwarz-300);
  --primitive-color-schwarz-400: var(--color-schwarz-400);
  --primitive-color-schwarz-500: var(--color-schwarz-500);
  --primitive-color-schwarz-600: var(--color-schwarz-600);
  --primitive-color-schwarz-700: var(--color-schwarz-700);
  --primitive-color-schwarz-800: var(--color-schwarz-800);
  --primitive-color-schwarz-900: var(--color-schwarz-900);
  --primitive-color-weiss-50: var(--color-weiss-50);
  --primitive-color-weiss-100: var(--color-weiss-100);
  --primitive-color-weiss-200: var(--color-weiss-200);
  --primitive-color-weiss-300: var(--color-weiss-300);
  --primitive-color-weiss-400: var(--color-weiss-400);
  --primitive-color-weiss-500: var(--color-weiss-500);
  --primitive-color-weiss-600: var(--color-weiss-600);
  --primitive-color-weiss-700: var(--color-weiss-700);
  --primitive-color-weiss-800: var(--color-weiss-800);
  --primitive-color-weiss-900: var(--color-weiss-900);
  --primitive-color-rot-signal-red-50: var(--color-rot-signal-red-50);
  --primitive-color-rot-signal-red-100: var(--color-rot-signal-red-100);
  --primitive-color-rot-signal-red-200: var(--color-rot-signal-red-200);
  --primitive-color-rot-signal-red-300: var(--color-rot-signal-red-300);
  --primitive-color-rot-signal-red-400: var(--color-rot-signal-red-400);
  --primitive-color-rot-signal-red-500: var(--color-rot-signal-red-500);
  --primitive-color-rot-signal-red-600: var(--color-rot-signal-red-600);
  --primitive-color-rot-signal-red-700: var(--color-rot-signal-red-700);
  --primitive-color-rot-signal-red-800: var(--color-rot-signal-red-800);
  --primitive-color-rot-signal-red-900: var(--color-rot-signal-red-900);
  --primitive-color-mittelgrau-50: var(--color-mittelgrau-50);
  --primitive-color-mittelgrau-100: var(--color-mittelgrau-100);
  --primitive-color-mittelgrau-200: var(--color-mittelgrau-200);
  --primitive-color-mittelgrau-300: var(--color-mittelgrau-300);
  --primitive-color-mittelgrau-400: var(--color-mittelgrau-400);
  --primitive-color-mittelgrau-500: var(--color-mittelgrau-500);
  --primitive-color-mittelgrau-600: var(--color-mittelgrau-600);
  --primitive-color-mittelgrau-700: var(--color-mittelgrau-700);
  --primitive-color-mittelgrau-800: var(--color-mittelgrau-800);
  --primitive-color-mittelgrau-900: var(--color-mittelgrau-900);
  --primitive-color-hellgrau-50: var(--color-hellgrau-50);
  --primitive-color-hellgrau-100: var(--color-hellgrau-100);
  --primitive-color-hellgrau-200: var(--color-hellgrau-200);
  --primitive-color-hellgrau-300: var(--color-hellgrau-300);
  --primitive-color-hellgrau-400: var(--color-hellgrau-400);
  --primitive-color-hellgrau-500: var(--color-hellgrau-500);
  --primitive-color-hellgrau-600: var(--color-hellgrau-600);
  --primitive-color-hellgrau-700: var(--color-hellgrau-700);
  --primitive-color-hellgrau-800: var(--color-hellgrau-800);
  --primitive-color-hellgrau-900: var(--color-hellgrau-900);
  --primitive-color-dunkelblau-50: var(--color-dunkelblau-50);
  --primitive-color-dunkelblau-100: var(--color-dunkelblau-100);
  --primitive-color-dunkelblau-200: var(--color-dunkelblau-200);
  --primitive-color-dunkelblau-300: var(--color-dunkelblau-300);
  --primitive-color-dunkelblau-400: var(--color-dunkelblau-400);
  --primitive-color-dunkelblau-500: var(--color-dunkelblau-500);
  --primitive-color-dunkelblau-600: var(--color-dunkelblau-600);
  --primitive-color-dunkelblau-700: var(--color-dunkelblau-700);
  --primitive-color-dunkelblau-800: var(--color-dunkelblau-800);
  --primitive-color-dunkelblau-900: var(--color-dunkelblau-900);
  --primitive-color-neutral-50: var(--color-neutral-50);
  --primitive-color-neutral-100: var(--color-neutral-100);
  --primitive-color-neutral-200: var(--color-neutral-200);
  --primitive-color-neutral-300: var(--color-neutral-300);
  --primitive-color-neutral-400: var(--color-neutral-400);
  --primitive-color-neutral-500: var(--color-neutral-500);
  --primitive-color-neutral-600: var(--color-neutral-600);
  --primitive-color-neutral-700: var(--color-neutral-700);
  --primitive-color-neutral-800: var(--color-neutral-800);
  --primitive-color-neutral-900: var(--color-neutral-900);
  --primitive-color-accent-50: var(--color-accent-50);
  --primitive-color-accent-100: var(--color-accent-100);
  --primitive-color-accent-200: var(--color-accent-200);
  --primitive-color-accent-300: var(--color-accent-300);
  --primitive-color-accent-400: var(--color-accent-400);
  --primitive-color-accent-500: var(--color-accent-500);
  --primitive-color-accent-600: var(--color-accent-600);
  --primitive-color-accent-700: var(--color-accent-700);
  --primitive-color-accent-800: var(--color-accent-800);
  --primitive-color-accent-900: var(--color-accent-900);

  /* Semantic tokens */
  /* Page background */
  --background-canvas: var(--primitive-color-neutral-50);
  /* Card/surface background */
  --background-surface: #FFFFFF;
  /* Muted background */
  --background-muted: var(--primitive-color-neutral-100);
  /* Primary text */
  --text-primary: var(--primitive-color-neutral-900);
  /* Secondary text */
  --text-secondary: var(--primitive-color-neutral-600);
  /* Muted/disabled text */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on dark backgrounds */
  --text-inverse: var(--primitive-color-neutral-50);
  /* Primary interactive (buttons, links) */
  --interactive-primary: var(--primitive-color-schwarz-500);
  /* Primary interactive hover */
  --interactive-primary-hover: var(--primitive-color-schwarz-600);
  /* Primary interactive active */
  --interactive-primary-active: var(--primitive-color-schwarz-700);
  /* Default border */
  --border-default: var(--primitive-color-neutral-200);
  /* Strong border */
  --border-strong: var(--primitive-color-neutral-400);
  /* Error — WCAG-compliant red */
  --status-error: #DC2626;
  /* Success — WCAG-compliant green */
  --status-success: #16A34A;
  /* Warning — WCAG AA amber (4.5:1+ on white) */
  --status-warning: #A16207;
  /* Info status */
  --status-info: var(--primitive-color-schwarz-500);
  /* Focus ring color */
  --focus-ring: var(--primitive-color-schwarz-500);
  /* Keyboard focus indicator */
  --accessibility-focus-visible: var(--primitive-color-schwarz-500);
}

/* Dark mode semantic tokens */
[data-theme="dark"] {
  /* Page background — dark */
  --background-canvas: var(--primitive-color-neutral-900);
  /* Card/surface — dark */
  --background-surface: var(--primitive-color-neutral-800);
  /* Muted background — dark */
  --background-muted: var(--primitive-color-neutral-700);
  /* Primary text — dark */
  --text-primary: var(--primitive-color-neutral-50);
  /* Secondary text — dark */
  --text-secondary: var(--primitive-color-neutral-300);
  /* Muted text — dark */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on light backgrounds — dark */
  --text-inverse: var(--primitive-color-neutral-900);
  /* Primary interactive — dark */
  --interactive-primary: var(--primitive-color-rot-signal-red-400);
  /* Primary hover — dark */
  --interactive-primary-hover: var(--primitive-color-rot-signal-red-300);
  /* Primary active — dark */
  --interactive-primary-active: var(--primitive-color-rot-signal-red-200);
  /* Default border — dark */
  --border-default: var(--primitive-color-neutral-700);
  /* Strong border — dark */
  --border-strong: var(--primitive-color-neutral-500);
  /* Error — WCAG-compliant red (dark) */
  --status-error: #EF4444;
  /* Success — WCAG-compliant green (dark) */
  --status-success: #22C55E;
  /* Warning — WCAG-compliant amber (dark) */
  --status-warning: #EAB308;
  /* Info — dark */
  --status-info: var(--primitive-color-rot-signal-red-400);
  /* Focus ring — dark */
  --focus-ring: var(--primitive-color-rot-signal-red-400);
  /* Keyboard focus — dark */
  --accessibility-focus-visible: var(--primitive-color-rot-signal-red-400);
}
`;
