// Auto-generated by scripts/generate-themes.ts — do not edit
export const css = `/* ═══════════════════════════════════════════════════════════════
 * nordic-modern — Design Tokens
 * Generated by @syncupsuite/transformers
 *
 * CONSUMER API — Use these semantic tokens in your styles:
 *
 * Backgrounds:  var(--background-canvas | surface | muted)
 * Text:         var(--text-primary | secondary | muted | inverse)
 * Interactive:  var(--interactive-primary | primary-hover | primary-active)
 * Borders:      var(--border-default | strong)
 * Status:       var(--status-error | success | warning | info)
 * Focus:        var(--focus-ring)
 *
 * Dark mode:    Add [data-theme="dark"] to a parent element.
 * Primitives:   --primitive-color-*, --primitive-spacing-*, etc.
 * ═══════════════════════════════════════════════════════════════ */

:root {
  /* --- Primitive Colors --- */
  /* Fjordblå 50 */
  --primitive-color-fjordbl-50: #EAF7FF;
  /* Fjordblå 100 */
  --primitive-color-fjordbl-100: #C2D7E8;
  /* Fjordblå 200 */
  --primitive-color-fjordbl-200: #9CB8CE;
  /* Fjordblå 300 */
  --primitive-color-fjordbl-300: #769AB5;
  /* Fjordblå 400 */
  --primitive-color-fjordbl-400: #517C9C;
  /* Fjordblå 500 */
  --primitive-color-fjordbl-500: #2B5F83;
  /* Fjordblå 600 */
  --primitive-color-fjordbl-600: #184665;
  /* Fjordblå 700 */
  --primitive-color-fjordbl-700: #052F49;
  /* Fjordblå 800 */
  --primitive-color-fjordbl-800: #001A2F;
  /* Fjordblå 900 */
  --primitive-color-fjordbl-900: #000616;
  /* Bjørkehvit (Birch White) 50 */
  --primitive-color-bj-rkehvit-birch-white-50: #F6F5F4;
  /* Bjørkehvit (Birch White) 100 */
  --primitive-color-bj-rkehvit-birch-white-100: #F5F4F3;
  /* Bjørkehvit (Birch White) 200 */
  --primitive-color-bj-rkehvit-birch-white-200: #F5F4F2;
  /* Bjørkehvit (Birch White) 300 */
  --primitive-color-bj-rkehvit-birch-white-300: #F5F3F0;
  /* Bjørkehvit (Birch White) 400 */
  --primitive-color-bj-rkehvit-birch-white-400: #F5F3EF;
  /* Bjørkehvit (Birch White) 500 */
  --primitive-color-bj-rkehvit-birch-white-500: #F5F2EE;
  /* Bjørkehvit (Birch White) 600 */
  --primitive-color-bj-rkehvit-birch-white-600: #B0AEAB;
  /* Bjørkehvit (Birch White) 700 */
  --primitive-color-bj-rkehvit-birch-white-700: #716F6C;
  /* Bjørkehvit (Birch White) 800 */
  --primitive-color-bj-rkehvit-birch-white-800: #373533;
  /* Bjørkehvit (Birch White) 900 */
  --primitive-color-bj-rkehvit-birch-white-900: #060605;
  /* Mosegrønn (Moss Green) 50 */
  --primitive-color-mosegr-nn-moss-green-50: #EFF8F0;
  /* Mosegrønn (Moss Green) 100 */
  --primitive-color-mosegr-nn-moss-green-100: #D0DDD1;
  /* Mosegrønn (Moss Green) 200 */
  --primitive-color-mosegr-nn-moss-green-200: #B2C4B3;
  /* Mosegrønn (Moss Green) 300 */
  --primitive-color-mosegr-nn-moss-green-300: #95AB96;
  /* Mosegrønn (Moss Green) 400 */
  --primitive-color-mosegr-nn-moss-green-400: #789279;
  /* Mosegrønn (Moss Green) 500 */
  --primitive-color-mosegr-nn-moss-green-500: #5C7A5E;
  /* Mosegrønn (Moss Green) 600 */
  --primitive-color-mosegr-nn-moss-green-600: #415A43;
  /* Mosegrønn (Moss Green) 700 */
  --primitive-color-mosegr-nn-moss-green-700: #273D29;
  /* Mosegrønn (Moss Green) 800 */
  --primitive-color-mosegr-nn-moss-green-800: #0F2111;
  /* Mosegrønn (Moss Green) 900 */
  --primitive-color-mosegr-nn-moss-green-900: #000801;
  /* Multebær (Cloudberry) 50 */
  --primitive-color-multeb-r-cloudberry-50: #FFF1E1;
  /* Multebær (Cloudberry) 100 */
  --primitive-color-multeb-r-cloudberry-100: #F8DBC1;
  /* Multebær (Cloudberry) 200 */
  --primitive-color-multeb-r-cloudberry-200: #EBC4A1;
  /* Multebær (Cloudberry) 300 */
  --primitive-color-multeb-r-cloudberry-300: #DEAE81;
  /* Multebær (Cloudberry) 400 */
  --primitive-color-multeb-r-cloudberry-400: #D19760;
  /* Multebær (Cloudberry) 500 */
  --primitive-color-multeb-r-cloudberry-500: #C4813C;
  /* Multebær (Cloudberry) 600 */
  --primitive-color-multeb-r-cloudberry-600: #945B1B;
  /* Multebær (Cloudberry) 700 */
  --primitive-color-multeb-r-cloudberry-700: #673700;
  /* Multebær (Cloudberry) 800 */
  --primitive-color-multeb-r-cloudberry-800: #3D1600;
  /* Multebær (Cloudberry) 900 */
  --primitive-color-multeb-r-cloudberry-900: #160000;
  /* Granitt (Granite) 50 */
  --primitive-color-granitt-granite-50: #F4F5F6;
  /* Granitt (Granite) 100 */
  --primitive-color-granitt-granite-100: #DBDCDE;
  /* Granitt (Granite) 200 */
  --primitive-color-granitt-granite-200: #C1C3C6;
  /* Granitt (Granite) 300 */
  --primitive-color-granitt-granite-300: #A9ABAF;
  /* Granitt (Granite) 400 */
  --primitive-color-granitt-granite-400: #919498;
  /* Granitt (Granite) 500 */
  --primitive-color-granitt-granite-500: #7A7D82;
  /* Granitt (Granite) 600 */
  --primitive-color-granitt-granite-600: #595B60;
  /* Granitt (Granite) 700 */
  --primitive-color-granitt-granite-700: #3A3C3F;
  /* Granitt (Granite) 800 */
  --primitive-color-granitt-granite-800: #1D1F21;
  /* Granitt (Granite) 900 */
  --primitive-color-granitt-granite-900: #050607;
  /* Nordlys (Northern Light) 50 */
  --primitive-color-nordlys-northern-light-50: #E7F9F9;
  /* Nordlys (Northern Light) 100 */
  --primitive-color-nordlys-northern-light-100: #C3E0DF;
  /* Nordlys (Northern Light) 200 */
  --primitive-color-nordlys-northern-light-200: #9FC7C6;
  /* Nordlys (Northern Light) 300 */
  --primitive-color-nordlys-northern-light-300: #7BAEAD;
  /* Nordlys (Northern Light) 400 */
  --primitive-color-nordlys-northern-light-400: #579695;
  /* Nordlys (Northern Light) 500 */
  --primitive-color-nordlys-northern-light-500: #2E7E7E;
  /* Nordlys (Northern Light) 600 */
  --primitive-color-nordlys-northern-light-600: #135E5E;
  /* Nordlys (Northern Light) 700 */
  --primitive-color-nordlys-northern-light-700: #003F40;
  /* Nordlys (Northern Light) 800 */
  --primitive-color-nordlys-northern-light-800: #002324;
  /* Nordlys (Northern Light) 900 */
  --primitive-color-nordlys-northern-light-900: #000A0B;
  /* Neutral 50 */
  --primitive-color-neutral-50: #F3F9FF;
  /* Neutral 100 */
  --primitive-color-neutral-100: #E9EFF5;
  /* Neutral 200 */
  --primitive-color-neutral-200: #D8DFE4;
  /* Neutral 300 */
  --primitive-color-neutral-300: #BFC5CA;
  /* Neutral 400 */
  --primitive-color-neutral-400: #93999E;
  /* Neutral 500 */
  --primitive-color-neutral-500: #6A6F74;
  /* Neutral 600 */
  --primitive-color-neutral-600: #484E52;
  /* Neutral 700 */
  --primitive-color-neutral-700: #2E3438;
  /* Neutral 800 */
  --primitive-color-neutral-800: #171B1F;
  /* Neutral 900 */
  --primitive-color-neutral-900: #05080B;
  /* Accent 50 */
  --primitive-color-accent-50: #EDF4FF;
  /* Accent 100 */
  --primitive-color-accent-100: #C1CCF1;
  /* Accent 200 */
  --primitive-color-accent-200: #97A4D6;
  /* Accent 300 */
  --primitive-color-accent-300: #707EBB;
  /* Accent 400 */
  --primitive-color-accent-400: #4B589F;
  /* Accent 500 */
  --primitive-color-accent-500: #2A3283;
  /* Accent 600 */
  --primitive-color-accent-600: #1E236A;
  /* Accent 700 */
  --primitive-color-accent-700: #121551;
  /* Accent 800 */
  --primitive-color-accent-800: #08073A;
  /* Accent 900 */
  --primitive-color-accent-900: #030024;

  /* --- Typography --- */
  /* Heading font family */
  --primitive-typography-family-heading: "Inter", "Futura", system-ui, sans-serif;
  /* Body font family */
  --primitive-typography-family-body: "Inter", system-ui, sans-serif;
  /* Monospace font family */
  --primitive-typography-family-mono: "JetBrains Mono", "Fira Code", monospace;
  /* Font size xs */
  --primitive-typography-size-xs: 0.75rem;
  /* Font size sm */
  --primitive-typography-size-sm: 0.875rem;
  /* Font size base */
  --primitive-typography-size-base: 1rem;
  /* Font size lg */
  --primitive-typography-size-lg: 1.125rem;
  /* Font size xl */
  --primitive-typography-size-xl: 1.25rem;
  /* Font size 2xl */
  --primitive-typography-size-2xl: 1.5rem;
  /* Font size 3xl */
  --primitive-typography-size-3xl: 1.875rem;
  /* Font size 4xl */
  --primitive-typography-size-4xl: 2.25rem;
  /* Font weight normal */
  --primitive-typography-weight-normal: 400;
  /* Font weight medium */
  --primitive-typography-weight-medium: 500;
  /* Font weight semibold */
  --primitive-typography-weight-semibold: 600;
  /* Font weight bold */
  --primitive-typography-weight-bold: 700;
  /* Line height tight */
  --primitive-typography-lineHeight-tight: 1.25;
  /* Line height normal */
  --primitive-typography-lineHeight-normal: 1.5;
  /* Line height relaxed */
  --primitive-typography-lineHeight-relaxed: 1.75;

  /* --- Spacing --- */
  /* Spacing 0 (0px) */
  --primitive-spacing-0: 0px;
  /* Spacing 1 (4px) */
  --primitive-spacing-1: 4px;
  /* Spacing 2 (8px) */
  --primitive-spacing-2: 8px;
  /* Spacing 3 (12px) */
  --primitive-spacing-3: 12px;
  /* Spacing 4 (16px) */
  --primitive-spacing-4: 16px;
  /* Spacing 5 (20px) */
  --primitive-spacing-5: 20px;
  /* Spacing 6 (24px) */
  --primitive-spacing-6: 24px;
  /* Spacing 8 (32px) */
  --primitive-spacing-8: 32px;
  /* Spacing 10 (40px) */
  --primitive-spacing-10: 40px;
  /* Spacing 12 (48px) */
  --primitive-spacing-12: 48px;
  /* Spacing 16 (64px) */
  --primitive-spacing-16: 64px;
  /* Spacing 20 (80px) */
  --primitive-spacing-20: 80px;
  /* Spacing 0.5 (2px) */
  --primitive-spacing-0-5: 2px;
  /* Spacing 1.5 (6px) */
  --primitive-spacing-1-5: 6px;

  /* --- Border Radius --- */
  /* Border radius none */
  --primitive-radius-none: 0px;
  /* Border radius sm */
  --primitive-radius-sm: 4px;
  /* Border radius md */
  --primitive-radius-md: 8px;
  /* Border radius lg */
  --primitive-radius-lg: 12px;
  /* Border radius xl */
  --primitive-radius-xl: 16px;
  /* Border radius full */
  --primitive-radius-full: 9999px;

  /* --- Semantic Tokens (Light) --- */
  /* Page background */
  --background-canvas: var(--primitive-color-neutral-50);
  /* Card/surface background */
  --background-surface: #FFFFFF;
  /* Muted background */
  --background-muted: var(--primitive-color-neutral-100);
  /* Primary text */
  --text-primary: var(--primitive-color-neutral-900);
  /* Secondary text */
  --text-secondary: var(--primitive-color-neutral-600);
  /* Muted/disabled text */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on dark backgrounds */
  --text-inverse: var(--primitive-color-neutral-50);
  /* Primary interactive (buttons, links) */
  --interactive-primary: var(--primitive-color-fjordbl-500);
  /* Primary interactive hover */
  --interactive-primary-hover: var(--primitive-color-fjordbl-600);
  /* Primary interactive active */
  --interactive-primary-active: var(--primitive-color-fjordbl-700);
  /* Default border */
  --border-default: var(--primitive-color-neutral-200);
  /* Strong border */
  --border-strong: var(--primitive-color-neutral-400);
  /* Error — WCAG-compliant red */
  --status-error: #DC2626;
  /* Success — WCAG-compliant green */
  --status-success: #16A34A;
  /* Warning — WCAG AA amber (4.5:1+ on white) */
  --status-warning: #A16207;
  /* Info status */
  --status-info: var(--primitive-color-fjordbl-500);
  /* Focus ring color */
  --focus-ring: var(--primitive-color-fjordbl-500);
  /* Keyboard focus indicator */
  --accessibility-focus-visible: var(--primitive-color-fjordbl-500);
}

[data-theme="dark"] {
  /* Page background — dark */
  --background-canvas: var(--primitive-color-neutral-900);
  /* Card/surface — dark */
  --background-surface: var(--primitive-color-neutral-800);
  /* Muted background — dark */
  --background-muted: var(--primitive-color-neutral-700);
  /* Primary text — dark */
  --text-primary: var(--primitive-color-neutral-50);
  /* Secondary text — dark */
  --text-secondary: var(--primitive-color-neutral-300);
  /* Muted text — dark */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on light backgrounds — dark */
  --text-inverse: var(--primitive-color-neutral-900);
  /* Primary interactive — dark */
  --interactive-primary: var(--primitive-color-fjordbl-400);
  /* Primary hover — dark */
  --interactive-primary-hover: var(--primitive-color-fjordbl-300);
  /* Primary active — dark */
  --interactive-primary-active: var(--primitive-color-fjordbl-200);
  /* Default border — dark */
  --border-default: var(--primitive-color-neutral-700);
  /* Strong border — dark */
  --border-strong: var(--primitive-color-neutral-500);
  /* Error — WCAG-compliant red (dark) */
  --status-error: #EF4444;
  /* Success — WCAG-compliant green (dark) */
  --status-success: #22C55E;
  /* Warning — WCAG-compliant amber (dark) */
  --status-warning: #EAB308;
  /* Info — dark */
  --status-info: var(--primitive-color-fjordbl-400);
  /* Focus ring — dark */
  --focus-ring: var(--primitive-color-fjordbl-400);
  /* Keyboard focus — dark */
  --accessibility-focus-visible: var(--primitive-color-fjordbl-400);
}
`;
export const tailwindCss = `@import "tailwindcss";

@theme {
  /* --- Colors --- */
  /* Fjordblå 50 */
  --color-fjordbl-50: #EAF7FF;
  /* Fjordblå 100 */
  --color-fjordbl-100: #C2D7E8;
  /* Fjordblå 200 */
  --color-fjordbl-200: #9CB8CE;
  /* Fjordblå 300 */
  --color-fjordbl-300: #769AB5;
  /* Fjordblå 400 */
  --color-fjordbl-400: #517C9C;
  /* Fjordblå 500 */
  --color-fjordbl-500: #2B5F83;
  /* Fjordblå 600 */
  --color-fjordbl-600: #184665;
  /* Fjordblå 700 */
  --color-fjordbl-700: #052F49;
  /* Fjordblå 800 */
  --color-fjordbl-800: #001A2F;
  /* Fjordblå 900 */
  --color-fjordbl-900: #000616;
  /* Bjørkehvit (Birch White) 50 */
  --color-bj-rkehvit-birch-white-50: #F6F5F4;
  /* Bjørkehvit (Birch White) 100 */
  --color-bj-rkehvit-birch-white-100: #F5F4F3;
  /* Bjørkehvit (Birch White) 200 */
  --color-bj-rkehvit-birch-white-200: #F5F4F2;
  /* Bjørkehvit (Birch White) 300 */
  --color-bj-rkehvit-birch-white-300: #F5F3F0;
  /* Bjørkehvit (Birch White) 400 */
  --color-bj-rkehvit-birch-white-400: #F5F3EF;
  /* Bjørkehvit (Birch White) 500 */
  --color-bj-rkehvit-birch-white-500: #F5F2EE;
  /* Bjørkehvit (Birch White) 600 */
  --color-bj-rkehvit-birch-white-600: #B0AEAB;
  /* Bjørkehvit (Birch White) 700 */
  --color-bj-rkehvit-birch-white-700: #716F6C;
  /* Bjørkehvit (Birch White) 800 */
  --color-bj-rkehvit-birch-white-800: #373533;
  /* Bjørkehvit (Birch White) 900 */
  --color-bj-rkehvit-birch-white-900: #060605;
  /* Mosegrønn (Moss Green) 50 */
  --color-mosegr-nn-moss-green-50: #EFF8F0;
  /* Mosegrønn (Moss Green) 100 */
  --color-mosegr-nn-moss-green-100: #D0DDD1;
  /* Mosegrønn (Moss Green) 200 */
  --color-mosegr-nn-moss-green-200: #B2C4B3;
  /* Mosegrønn (Moss Green) 300 */
  --color-mosegr-nn-moss-green-300: #95AB96;
  /* Mosegrønn (Moss Green) 400 */
  --color-mosegr-nn-moss-green-400: #789279;
  /* Mosegrønn (Moss Green) 500 */
  --color-mosegr-nn-moss-green-500: #5C7A5E;
  /* Mosegrønn (Moss Green) 600 */
  --color-mosegr-nn-moss-green-600: #415A43;
  /* Mosegrønn (Moss Green) 700 */
  --color-mosegr-nn-moss-green-700: #273D29;
  /* Mosegrønn (Moss Green) 800 */
  --color-mosegr-nn-moss-green-800: #0F2111;
  /* Mosegrønn (Moss Green) 900 */
  --color-mosegr-nn-moss-green-900: #000801;
  /* Multebær (Cloudberry) 50 */
  --color-multeb-r-cloudberry-50: #FFF1E1;
  /* Multebær (Cloudberry) 100 */
  --color-multeb-r-cloudberry-100: #F8DBC1;
  /* Multebær (Cloudberry) 200 */
  --color-multeb-r-cloudberry-200: #EBC4A1;
  /* Multebær (Cloudberry) 300 */
  --color-multeb-r-cloudberry-300: #DEAE81;
  /* Multebær (Cloudberry) 400 */
  --color-multeb-r-cloudberry-400: #D19760;
  /* Multebær (Cloudberry) 500 */
  --color-multeb-r-cloudberry-500: #C4813C;
  /* Multebær (Cloudberry) 600 */
  --color-multeb-r-cloudberry-600: #945B1B;
  /* Multebær (Cloudberry) 700 */
  --color-multeb-r-cloudberry-700: #673700;
  /* Multebær (Cloudberry) 800 */
  --color-multeb-r-cloudberry-800: #3D1600;
  /* Multebær (Cloudberry) 900 */
  --color-multeb-r-cloudberry-900: #160000;
  /* Granitt (Granite) 50 */
  --color-granitt-granite-50: #F4F5F6;
  /* Granitt (Granite) 100 */
  --color-granitt-granite-100: #DBDCDE;
  /* Granitt (Granite) 200 */
  --color-granitt-granite-200: #C1C3C6;
  /* Granitt (Granite) 300 */
  --color-granitt-granite-300: #A9ABAF;
  /* Granitt (Granite) 400 */
  --color-granitt-granite-400: #919498;
  /* Granitt (Granite) 500 */
  --color-granitt-granite-500: #7A7D82;
  /* Granitt (Granite) 600 */
  --color-granitt-granite-600: #595B60;
  /* Granitt (Granite) 700 */
  --color-granitt-granite-700: #3A3C3F;
  /* Granitt (Granite) 800 */
  --color-granitt-granite-800: #1D1F21;
  /* Granitt (Granite) 900 */
  --color-granitt-granite-900: #050607;
  /* Nordlys (Northern Light) 50 */
  --color-nordlys-northern-light-50: #E7F9F9;
  /* Nordlys (Northern Light) 100 */
  --color-nordlys-northern-light-100: #C3E0DF;
  /* Nordlys (Northern Light) 200 */
  --color-nordlys-northern-light-200: #9FC7C6;
  /* Nordlys (Northern Light) 300 */
  --color-nordlys-northern-light-300: #7BAEAD;
  /* Nordlys (Northern Light) 400 */
  --color-nordlys-northern-light-400: #579695;
  /* Nordlys (Northern Light) 500 */
  --color-nordlys-northern-light-500: #2E7E7E;
  /* Nordlys (Northern Light) 600 */
  --color-nordlys-northern-light-600: #135E5E;
  /* Nordlys (Northern Light) 700 */
  --color-nordlys-northern-light-700: #003F40;
  /* Nordlys (Northern Light) 800 */
  --color-nordlys-northern-light-800: #002324;
  /* Nordlys (Northern Light) 900 */
  --color-nordlys-northern-light-900: #000A0B;
  /* Neutral 50 */
  --color-neutral-50: #F3F9FF;
  /* Neutral 100 */
  --color-neutral-100: #E9EFF5;
  /* Neutral 200 */
  --color-neutral-200: #D8DFE4;
  /* Neutral 300 */
  --color-neutral-300: #BFC5CA;
  /* Neutral 400 */
  --color-neutral-400: #93999E;
  /* Neutral 500 */
  --color-neutral-500: #6A6F74;
  /* Neutral 600 */
  --color-neutral-600: #484E52;
  /* Neutral 700 */
  --color-neutral-700: #2E3438;
  /* Neutral 800 */
  --color-neutral-800: #171B1F;
  /* Neutral 900 */
  --color-neutral-900: #05080B;
  /* Accent 50 */
  --color-accent-50: #EDF4FF;
  /* Accent 100 */
  --color-accent-100: #C1CCF1;
  /* Accent 200 */
  --color-accent-200: #97A4D6;
  /* Accent 300 */
  --color-accent-300: #707EBB;
  /* Accent 400 */
  --color-accent-400: #4B589F;
  /* Accent 500 */
  --color-accent-500: #2A3283;
  /* Accent 600 */
  --color-accent-600: #1E236A;
  /* Accent 700 */
  --color-accent-700: #121551;
  /* Accent 800 */
  --color-accent-800: #08073A;
  /* Accent 900 */
  --color-accent-900: #030024;

  /* --- Spacing (8px grid) --- */
  /* Spacing 0 (0px) */
  --spacing-0: 0px;
  /* Spacing 1 (4px) */
  --spacing-1: 4px;
  /* Spacing 2 (8px) */
  --spacing-2: 8px;
  /* Spacing 3 (12px) */
  --spacing-3: 12px;
  /* Spacing 4 (16px) */
  --spacing-4: 16px;
  /* Spacing 5 (20px) */
  --spacing-5: 20px;
  /* Spacing 6 (24px) */
  --spacing-6: 24px;
  /* Spacing 8 (32px) */
  --spacing-8: 32px;
  /* Spacing 10 (40px) */
  --spacing-10: 40px;
  /* Spacing 12 (48px) */
  --spacing-12: 48px;
  /* Spacing 16 (64px) */
  --spacing-16: 64px;
  /* Spacing 20 (80px) */
  --spacing-20: 80px;
  /* Spacing 0.5 (2px) */
  --spacing-0-5: 2px;
  /* Spacing 1.5 (6px) */
  --spacing-1-5: 6px;

  /* --- Font Families --- */
  /* Heading font family */
  --font-heading: "Inter", "Futura", system-ui, sans-serif;
  /* Body font family */
  --font-body: "Inter", system-ui, sans-serif;
  /* Monospace font family */
  --font-mono: "JetBrains Mono", "Fira Code", monospace;

  /* --- Font Sizes --- */
  /* Font size xs */
  --text-xs: 0.75rem;
  /* Font size sm */
  --text-sm: 0.875rem;
  /* Font size base */
  --text-base: 1rem;
  /* Font size lg */
  --text-lg: 1.125rem;
  /* Font size xl */
  --text-xl: 1.25rem;
  /* Font size 2xl */
  --text-2xl: 1.5rem;
  /* Font size 3xl */
  --text-3xl: 1.875rem;
  /* Font size 4xl */
  --text-4xl: 2.25rem;

  /* --- Border Radius --- */
  /* Border radius none */
  --radius-none: 0px;
  /* Border radius sm */
  --radius-sm: 4px;
  /* Border radius md */
  --radius-md: 8px;
  /* Border radius lg */
  --radius-lg: 12px;
  /* Border radius xl */
  --radius-xl: 16px;
  /* Border radius full */
  --radius-full: 9999px;

}

/* === Semantic Color API — theme-aware Tailwind utilities === */
@theme {
  --color-canvas: var(--background-canvas);
  --color-surface: var(--background-surface);
  --color-muted: var(--background-muted);
  --color-foreground: var(--text-primary);
  --color-foreground-secondary: var(--text-secondary);
  --color-foreground-muted: var(--text-muted);
  --color-foreground-inverse: var(--text-inverse);
  --color-primary: var(--interactive-primary);
  --color-primary-hover: var(--interactive-primary-hover);
  --color-primary-active: var(--interactive-primary-active);
  --color-border: var(--border-default);
  --color-border-strong: var(--border-strong);
  --color-error: var(--status-error);
  --color-success: var(--status-success);
  --color-warning: var(--status-warning);
  --color-info: var(--status-info);
  --color-ring: var(--focus-ring);
  --color-focus-visible: var(--accessibility-focus-visible);
}

/* Primitive aliases + light mode semantic tokens */
:root {
  /* --primitive-color-* aliases → @theme --color-* (for semantic var() resolution) */
  --primitive-color-fjordbl-50: var(--color-fjordbl-50);
  --primitive-color-fjordbl-100: var(--color-fjordbl-100);
  --primitive-color-fjordbl-200: var(--color-fjordbl-200);
  --primitive-color-fjordbl-300: var(--color-fjordbl-300);
  --primitive-color-fjordbl-400: var(--color-fjordbl-400);
  --primitive-color-fjordbl-500: var(--color-fjordbl-500);
  --primitive-color-fjordbl-600: var(--color-fjordbl-600);
  --primitive-color-fjordbl-700: var(--color-fjordbl-700);
  --primitive-color-fjordbl-800: var(--color-fjordbl-800);
  --primitive-color-fjordbl-900: var(--color-fjordbl-900);
  --primitive-color-bj-rkehvit-birch-white-50: var(--color-bj-rkehvit-birch-white-50);
  --primitive-color-bj-rkehvit-birch-white-100: var(--color-bj-rkehvit-birch-white-100);
  --primitive-color-bj-rkehvit-birch-white-200: var(--color-bj-rkehvit-birch-white-200);
  --primitive-color-bj-rkehvit-birch-white-300: var(--color-bj-rkehvit-birch-white-300);
  --primitive-color-bj-rkehvit-birch-white-400: var(--color-bj-rkehvit-birch-white-400);
  --primitive-color-bj-rkehvit-birch-white-500: var(--color-bj-rkehvit-birch-white-500);
  --primitive-color-bj-rkehvit-birch-white-600: var(--color-bj-rkehvit-birch-white-600);
  --primitive-color-bj-rkehvit-birch-white-700: var(--color-bj-rkehvit-birch-white-700);
  --primitive-color-bj-rkehvit-birch-white-800: var(--color-bj-rkehvit-birch-white-800);
  --primitive-color-bj-rkehvit-birch-white-900: var(--color-bj-rkehvit-birch-white-900);
  --primitive-color-mosegr-nn-moss-green-50: var(--color-mosegr-nn-moss-green-50);
  --primitive-color-mosegr-nn-moss-green-100: var(--color-mosegr-nn-moss-green-100);
  --primitive-color-mosegr-nn-moss-green-200: var(--color-mosegr-nn-moss-green-200);
  --primitive-color-mosegr-nn-moss-green-300: var(--color-mosegr-nn-moss-green-300);
  --primitive-color-mosegr-nn-moss-green-400: var(--color-mosegr-nn-moss-green-400);
  --primitive-color-mosegr-nn-moss-green-500: var(--color-mosegr-nn-moss-green-500);
  --primitive-color-mosegr-nn-moss-green-600: var(--color-mosegr-nn-moss-green-600);
  --primitive-color-mosegr-nn-moss-green-700: var(--color-mosegr-nn-moss-green-700);
  --primitive-color-mosegr-nn-moss-green-800: var(--color-mosegr-nn-moss-green-800);
  --primitive-color-mosegr-nn-moss-green-900: var(--color-mosegr-nn-moss-green-900);
  --primitive-color-multeb-r-cloudberry-50: var(--color-multeb-r-cloudberry-50);
  --primitive-color-multeb-r-cloudberry-100: var(--color-multeb-r-cloudberry-100);
  --primitive-color-multeb-r-cloudberry-200: var(--color-multeb-r-cloudberry-200);
  --primitive-color-multeb-r-cloudberry-300: var(--color-multeb-r-cloudberry-300);
  --primitive-color-multeb-r-cloudberry-400: var(--color-multeb-r-cloudberry-400);
  --primitive-color-multeb-r-cloudberry-500: var(--color-multeb-r-cloudberry-500);
  --primitive-color-multeb-r-cloudberry-600: var(--color-multeb-r-cloudberry-600);
  --primitive-color-multeb-r-cloudberry-700: var(--color-multeb-r-cloudberry-700);
  --primitive-color-multeb-r-cloudberry-800: var(--color-multeb-r-cloudberry-800);
  --primitive-color-multeb-r-cloudberry-900: var(--color-multeb-r-cloudberry-900);
  --primitive-color-granitt-granite-50: var(--color-granitt-granite-50);
  --primitive-color-granitt-granite-100: var(--color-granitt-granite-100);
  --primitive-color-granitt-granite-200: var(--color-granitt-granite-200);
  --primitive-color-granitt-granite-300: var(--color-granitt-granite-300);
  --primitive-color-granitt-granite-400: var(--color-granitt-granite-400);
  --primitive-color-granitt-granite-500: var(--color-granitt-granite-500);
  --primitive-color-granitt-granite-600: var(--color-granitt-granite-600);
  --primitive-color-granitt-granite-700: var(--color-granitt-granite-700);
  --primitive-color-granitt-granite-800: var(--color-granitt-granite-800);
  --primitive-color-granitt-granite-900: var(--color-granitt-granite-900);
  --primitive-color-nordlys-northern-light-50: var(--color-nordlys-northern-light-50);
  --primitive-color-nordlys-northern-light-100: var(--color-nordlys-northern-light-100);
  --primitive-color-nordlys-northern-light-200: var(--color-nordlys-northern-light-200);
  --primitive-color-nordlys-northern-light-300: var(--color-nordlys-northern-light-300);
  --primitive-color-nordlys-northern-light-400: var(--color-nordlys-northern-light-400);
  --primitive-color-nordlys-northern-light-500: var(--color-nordlys-northern-light-500);
  --primitive-color-nordlys-northern-light-600: var(--color-nordlys-northern-light-600);
  --primitive-color-nordlys-northern-light-700: var(--color-nordlys-northern-light-700);
  --primitive-color-nordlys-northern-light-800: var(--color-nordlys-northern-light-800);
  --primitive-color-nordlys-northern-light-900: var(--color-nordlys-northern-light-900);
  --primitive-color-neutral-50: var(--color-neutral-50);
  --primitive-color-neutral-100: var(--color-neutral-100);
  --primitive-color-neutral-200: var(--color-neutral-200);
  --primitive-color-neutral-300: var(--color-neutral-300);
  --primitive-color-neutral-400: var(--color-neutral-400);
  --primitive-color-neutral-500: var(--color-neutral-500);
  --primitive-color-neutral-600: var(--color-neutral-600);
  --primitive-color-neutral-700: var(--color-neutral-700);
  --primitive-color-neutral-800: var(--color-neutral-800);
  --primitive-color-neutral-900: var(--color-neutral-900);
  --primitive-color-accent-50: var(--color-accent-50);
  --primitive-color-accent-100: var(--color-accent-100);
  --primitive-color-accent-200: var(--color-accent-200);
  --primitive-color-accent-300: var(--color-accent-300);
  --primitive-color-accent-400: var(--color-accent-400);
  --primitive-color-accent-500: var(--color-accent-500);
  --primitive-color-accent-600: var(--color-accent-600);
  --primitive-color-accent-700: var(--color-accent-700);
  --primitive-color-accent-800: var(--color-accent-800);
  --primitive-color-accent-900: var(--color-accent-900);

  /* Semantic tokens */
  /* Page background */
  --background-canvas: var(--primitive-color-neutral-50);
  /* Card/surface background */
  --background-surface: #FFFFFF;
  /* Muted background */
  --background-muted: var(--primitive-color-neutral-100);
  /* Primary text */
  --text-primary: var(--primitive-color-neutral-900);
  /* Secondary text */
  --text-secondary: var(--primitive-color-neutral-600);
  /* Muted/disabled text */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on dark backgrounds */
  --text-inverse: var(--primitive-color-neutral-50);
  /* Primary interactive (buttons, links) */
  --interactive-primary: var(--primitive-color-fjordbl-500);
  /* Primary interactive hover */
  --interactive-primary-hover: var(--primitive-color-fjordbl-600);
  /* Primary interactive active */
  --interactive-primary-active: var(--primitive-color-fjordbl-700);
  /* Default border */
  --border-default: var(--primitive-color-neutral-200);
  /* Strong border */
  --border-strong: var(--primitive-color-neutral-400);
  /* Error — WCAG-compliant red */
  --status-error: #DC2626;
  /* Success — WCAG-compliant green */
  --status-success: #16A34A;
  /* Warning — WCAG AA amber (4.5:1+ on white) */
  --status-warning: #A16207;
  /* Info status */
  --status-info: var(--primitive-color-fjordbl-500);
  /* Focus ring color */
  --focus-ring: var(--primitive-color-fjordbl-500);
  /* Keyboard focus indicator */
  --accessibility-focus-visible: var(--primitive-color-fjordbl-500);
}

/* Dark mode semantic tokens */
[data-theme="dark"] {
  /* Page background — dark */
  --background-canvas: var(--primitive-color-neutral-900);
  /* Card/surface — dark */
  --background-surface: var(--primitive-color-neutral-800);
  /* Muted background — dark */
  --background-muted: var(--primitive-color-neutral-700);
  /* Primary text — dark */
  --text-primary: var(--primitive-color-neutral-50);
  /* Secondary text — dark */
  --text-secondary: var(--primitive-color-neutral-300);
  /* Muted text — dark */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on light backgrounds — dark */
  --text-inverse: var(--primitive-color-neutral-900);
  /* Primary interactive — dark */
  --interactive-primary: var(--primitive-color-fjordbl-400);
  /* Primary hover — dark */
  --interactive-primary-hover: var(--primitive-color-fjordbl-300);
  /* Primary active — dark */
  --interactive-primary-active: var(--primitive-color-fjordbl-200);
  /* Default border — dark */
  --border-default: var(--primitive-color-neutral-700);
  /* Strong border — dark */
  --border-strong: var(--primitive-color-neutral-500);
  /* Error — WCAG-compliant red (dark) */
  --status-error: #EF4444;
  /* Success — WCAG-compliant green (dark) */
  --status-success: #22C55E;
  /* Warning — WCAG-compliant amber (dark) */
  --status-warning: #EAB308;
  /* Info — dark */
  --status-info: var(--primitive-color-fjordbl-400);
  /* Focus ring — dark */
  --focus-ring: var(--primitive-color-fjordbl-400);
  /* Keyboard focus — dark */
  --accessibility-focus-visible: var(--primitive-color-fjordbl-400);
}
`;
