// Auto-generated by scripts/generate-themes.ts — do not edit
export const css = `/* nihon-no-iro-traditional — Design Tokens */
/* Generated by @syncupsuite/transformers */

:root {
  /* --- Primitive Colors --- */
  /* Hanada (縹) 50 */
  --primitive-color-hanada-50: #F1F2F4;
  /* Hanada (縹) 100 */
  --primitive-color-hanada-100: #E2E5E9;
  /* Hanada (縹) 200 */
  --primitive-color-hanada-200: #B7CBE1;
  /* Hanada (縹) 300 */
  --primitive-color-hanada-300: #93B0D2;
  /* Hanada (縹) 400 */
  --primitive-color-hanada-400: #6F96C3;
  /* Hanada (縹) 500 */
  --primitive-color-hanada-500: #2D4A6C;
  /* Hanada (縹) 600 */
  --primitive-color-hanada-600: #21374F;
  /* Hanada (縹) 700 */
  --primitive-color-hanada-700: #171E26;
  /* Hanada (縹) 800 */
  --primitive-color-hanada-800: #0D1216;
  /* Hanada (縹) 900 */
  --primitive-color-hanada-900: #080A0D;
  /* Sakura-nezumi (桜鼠) 50 */
  --primitive-color-sakura-nezumi-50: #F3F2F2;
  /* Sakura-nezumi (桜鼠) 100 */
  --primitive-color-sakura-nezumi-100: #E7E5E4;
  /* Sakura-nezumi (桜鼠) 200 */
  --primitive-color-sakura-nezumi-200: #D2C8C6;
  /* Sakura-nezumi (桜鼠) 300 */
  --primitive-color-sakura-nezumi-300: #BCADA9;
  /* Sakura-nezumi (桜鼠) 400 */
  --primitive-color-sakura-nezumi-400: #A5918D;
  /* Sakura-nezumi (桜鼠) 500 */
  --primitive-color-sakura-nezumi-500: #B5A4A1;
  /* Sakura-nezumi (桜鼠) 600 */
  --primitive-color-sakura-nezumi-600: #A38F8A;
  /* Sakura-nezumi (桜鼠) 700 */
  --primitive-color-sakura-nezumi-700: #8C736E;
  /* Sakura-nezumi (桜鼠) 800 */
  --primitive-color-sakura-nezumi-800: #6F5C58;
  /* Sakura-nezumi (桜鼠) 900 */
  --primitive-color-sakura-nezumi-900: #534441;
  /* Wasurenagusa-iro (勿忘草色) 50 */
  --primitive-color-wasurenagusa-iro-50: #F1F3F4;
  /* Wasurenagusa-iro (勿忘草色) 100 */
  --primitive-color-wasurenagusa-iro-100: #E2E6E9;
  /* Wasurenagusa-iro (勿忘草色) 200 */
  --primitive-color-wasurenagusa-iro-200: #B6D0E2;
  /* Wasurenagusa-iro (勿忘草色) 300 */
  --primitive-color-wasurenagusa-iro-300: #91B8D4;
  /* Wasurenagusa-iro (勿忘草色) 400 */
  --primitive-color-wasurenagusa-iro-400: #6CA0C6;
  /* Wasurenagusa-iro (勿忘草色) 500 */
  --primitive-color-wasurenagusa-iro-500: #7BAACC;
  /* Wasurenagusa-iro (勿忘草色) 600 */
  --primitive-color-wasurenagusa-iro-600: #5D97C0;
  /* Wasurenagusa-iro (勿忘草色) 700 */
  --primitive-color-wasurenagusa-iro-700: #427EA9;
  /* Wasurenagusa-iro (勿忘草色) 800 */
  --primitive-color-wasurenagusa-iro-800: #336384;
  /* Wasurenagusa-iro (勿忘草色) 900 */
  --primitive-color-wasurenagusa-iro-900: #25475F;
  /* Kitsune-iro (狐色) 50 */
  --primitive-color-kitsune-iro-50: #F4F3F1;
  /* Kitsune-iro (狐色) 100 */
  --primitive-color-kitsune-iro-100: #E9E7E2;
  /* Kitsune-iro (狐色) 200 */
  --primitive-color-kitsune-iro-200: #E2D4B6;
  /* Kitsune-iro (狐色) 300 */
  --primitive-color-kitsune-iro-300: #D4BF91;
  /* Kitsune-iro (狐色) 400 */
  --primitive-color-kitsune-iro-400: #C6A96C;
  /* Kitsune-iro (狐色) 500 */
  --primitive-color-kitsune-iro-500: #C6A96C;
  /* Kitsune-iro (狐色) 600 */
  --primitive-color-kitsune-iro-600: #BA984F;
  /* Kitsune-iro (狐色) 700 */
  --primitive-color-kitsune-iro-700: #9A7C3C;
  /* Kitsune-iro (狐色) 800 */
  --primitive-color-kitsune-iro-800: #765F2E;
  /* Kitsune-iro (狐色) 900 */
  --primitive-color-kitsune-iro-900: #51411F;
  /* Enji (臙脂) 50 */
  --primitive-color-enji-50: #F4F0F1;
  /* Enji (臙脂) 100 */
  --primitive-color-enji-100: #E9E2E3;
  /* Enji (臙脂) 200 */
  --primitive-color-enji-200: #E3B5BA;
  /* Enji (臙脂) 300 */
  --primitive-color-enji-300: #D59098;
  /* Enji (臙脂) 400 */
  --primitive-color-enji-400: #C76B76;
  /* Enji (臙脂) 500 */
  --primitive-color-enji-500: #9B3B46;
  /* Enji (臙脂) 600 */
  --primitive-color-enji-600: #7E3039;
  /* Enji (臙脂) 700 */
  --primitive-color-enji-700: #592228;
  /* Enji (臙脂) 800 */
  --primitive-color-enji-800: #2D1A1C;
  /* Enji (臙脂) 900 */
  --primitive-color-enji-900: #0D0708;
  /* Rikyuu-nezumi (利休鼠) 50 */
  --primitive-color-rikyuu-nezumi-50: #F2F2F2;
  /* Rikyuu-nezumi (利休鼠) 100 */
  --primitive-color-rikyuu-nezumi-100: #E6E6E5;
  /* Rikyuu-nezumi (利休鼠) 200 */
  --primitive-color-rikyuu-nezumi-200: #CDCECA;
  /* Rikyuu-nezumi (利休鼠) 300 */
  --primitive-color-rikyuu-nezumi-300: #B4B6AF;
  /* Rikyuu-nezumi (利休鼠) 400 */
  --primitive-color-rikyuu-nezumi-400: #9A9D95;
  /* Rikyuu-nezumi (利休鼠) 500 */
  --primitive-color-rikyuu-nezumi-500: #797D73;
  /* Rikyuu-nezumi (利休鼠) 600 */
  --primitive-color-rikyuu-nezumi-600: #65675F;
  /* Rikyuu-nezumi (利休鼠) 700 */
  --primitive-color-rikyuu-nezumi-700: #4B4D47;
  /* Rikyuu-nezumi (利休鼠) 800 */
  --primitive-color-rikyuu-nezumi-800: #31322F;
  /* Rikyuu-nezumi (利休鼠) 900 */
  --primitive-color-rikyuu-nezumi-900: #171716;
  /* Shironeri (白練) 50 */
  --primitive-color-shironeri-50: #F4F3F0;
  /* Shironeri (白練) 100 */
  --primitive-color-shironeri-100: #E9E7E2;
  /* Shironeri (白練) 200 */
  --primitive-color-shironeri-200: #E5D6B3;
  /* Shironeri (白練) 300 */
  --primitive-color-shironeri-300: #D8C18D;
  /* Shironeri (白練) 400 */
  --primitive-color-shironeri-400: #CBAD67;
  /* Shironeri (白練) 500 */
  --primitive-color-shironeri-500: #EBE9E5;
  /* Shironeri (白練) 600 */
  --primitive-color-shironeri-600: #E9DCBE;
  /* Shironeri (白練) 700 */
  --primitive-color-shironeri-700: #DCC898;
  /* Shironeri (白練) 800 */
  --primitive-color-shironeri-800: #CFB372;
  /* Shironeri (白練) 900 */
  --primitive-color-shironeri-900: #C29F4C;
  /* Neutral 50 */
  --primitive-color-neutral-50: #F7F7F8;
  /* Neutral 100 */
  --primitive-color-neutral-100: #EFF0F0;
  /* Neutral 200 */
  --primitive-color-neutral-200: #DFE0E2;
  /* Neutral 300 */
  --primitive-color-neutral-300: #C5C7C9;
  /* Neutral 400 */
  --primitive-color-neutral-400: #9A9EA2;
  /* Neutral 500 */
  --primitive-color-neutral-500: #71757A;
  /* Neutral 600 */
  --primitive-color-neutral-600: #585C5F;
  /* Neutral 700 */
  --primitive-color-neutral-700: #404245;
  /* Neutral 800 */
  --primitive-color-neutral-800: #27292A;
  /* Neutral 900 */
  --primitive-color-neutral-900: #141415;
  /* Accent 50 */
  --primitive-color-accent-50: #F3F4F1;
  /* Accent 100 */
  --primitive-color-accent-100: #E7E9E2;
  /* Accent 200 */
  --primitive-color-accent-200: #D7E1B7;
  /* Accent 300 */
  --primitive-color-accent-300: #C3D293;
  /* Accent 400 */
  --primitive-color-accent-400: #AFC36F;
  /* Accent 500 */
  --primitive-color-accent-500: #5D6C2D;
  /* Accent 600 */
  --primitive-color-accent-600: #444F21;
  /* Accent 700 */
  --primitive-color-accent-700: #232617;
  /* Accent 800 */
  --primitive-color-accent-800: #14160D;
  /* Accent 900 */
  --primitive-color-accent-900: #0C0D08;

  /* --- Typography --- */
  /* Heading font family */
  --primitive-typography-family-heading: "Noto Serif JP", "Noto Serif", Georgia, serif;
  /* Body font family */
  --primitive-typography-family-body: "Noto Serif JP", "Noto Serif", Georgia, serif;
  /* Monospace font family */
  --primitive-typography-family-mono: "JetBrains Mono", "Fira Code", monospace;
  /* Font size xs */
  --primitive-typography-size-xs: 0.75rem;
  /* Font size sm */
  --primitive-typography-size-sm: 0.875rem;
  /* Font size base */
  --primitive-typography-size-base: 1rem;
  /* Font size lg */
  --primitive-typography-size-lg: 1.125rem;
  /* Font size xl */
  --primitive-typography-size-xl: 1.25rem;
  /* Font size 2xl */
  --primitive-typography-size-2xl: 1.5rem;
  /* Font size 3xl */
  --primitive-typography-size-3xl: 1.875rem;
  /* Font size 4xl */
  --primitive-typography-size-4xl: 2.25rem;
  /* Font weight normal */
  --primitive-typography-weight-normal: 400;
  /* Font weight medium */
  --primitive-typography-weight-medium: 500;
  /* Font weight semibold */
  --primitive-typography-weight-semibold: 600;
  /* Font weight bold */
  --primitive-typography-weight-bold: 700;
  /* Line height tight */
  --primitive-typography-lineHeight-tight: 1.25;
  /* Line height normal */
  --primitive-typography-lineHeight-normal: 1.5;
  /* Line height relaxed */
  --primitive-typography-lineHeight-relaxed: 1.75;

  /* --- Spacing --- */
  /* Spacing 0 (0px) */
  --primitive-spacing-0: 0px;
  /* Spacing 1 (4px) */
  --primitive-spacing-1: 4px;
  /* Spacing 2 (8px) */
  --primitive-spacing-2: 8px;
  /* Spacing 3 (12px) */
  --primitive-spacing-3: 12px;
  /* Spacing 4 (16px) */
  --primitive-spacing-4: 16px;
  /* Spacing 5 (20px) */
  --primitive-spacing-5: 20px;
  /* Spacing 6 (24px) */
  --primitive-spacing-6: 24px;
  /* Spacing 8 (32px) */
  --primitive-spacing-8: 32px;
  /* Spacing 10 (40px) */
  --primitive-spacing-10: 40px;
  /* Spacing 12 (48px) */
  --primitive-spacing-12: 48px;
  /* Spacing 16 (64px) */
  --primitive-spacing-16: 64px;
  /* Spacing 20 (80px) */
  --primitive-spacing-20: 80px;
  /* Spacing 0.5 (2px) */
  --primitive-spacing-0-5: 2px;
  /* Spacing 1.5 (6px) */
  --primitive-spacing-1-5: 6px;

  /* --- Border Radius --- */
  /* Border radius none */
  --primitive-radius-none: 0px;
  /* Border radius sm */
  --primitive-radius-sm: 2px;
  /* Border radius md */
  --primitive-radius-md: 4px;
  /* Border radius lg */
  --primitive-radius-lg: 6px;
  /* Border radius xl */
  --primitive-radius-xl: 8px;
  /* Border radius full */
  --primitive-radius-full: 9999px;

  /* --- Semantic Tokens (Light) --- */
  /* Page background */
  --background-canvas: var(--primitive-color-neutral-50);
  /* Card/surface background */
  --background-surface: #FFFFFF;
  /* Muted background */
  --background-muted: var(--primitive-color-neutral-100);
  /* Primary text */
  --text-primary: var(--primitive-color-neutral-900);
  /* Secondary text */
  --text-secondary: var(--primitive-color-neutral-600);
  /* Muted/disabled text */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on dark backgrounds */
  --text-inverse: var(--primitive-color-neutral-50);
  /* Primary interactive (buttons, links) */
  --interactive-primary: var(--primitive-color-hanada-500);
  /* Primary interactive hover */
  --interactive-primary-hover: var(--primitive-color-hanada-600);
  /* Primary interactive active */
  --interactive-primary-active: var(--primitive-color-hanada-700);
  /* Default border */
  --border-default: var(--primitive-color-neutral-200);
  /* Strong border */
  --border-strong: var(--primitive-color-neutral-400);
  /* Error — WCAG-compliant red */
  --status-error: #DC2626;
  /* Success — WCAG-compliant green */
  --status-success: #16A34A;
  /* Warning — WCAG-compliant amber */
  --status-warning: #CA8A04;
  /* Info status */
  --status-info: var(--primitive-color-hanada-500);
  /* Focus ring color */
  --focus-ring: var(--primitive-color-hanada-500);
  /* Keyboard focus indicator */
  --accessibility-focus-visible: var(--primitive-color-hanada-500);
}

[data-theme="dark"] {
  /* Page background — dark */
  --background-canvas: var(--primitive-color-neutral-900);
  /* Card/surface — dark */
  --background-surface: var(--primitive-color-neutral-800);
  /* Muted background — dark */
  --background-muted: var(--primitive-color-neutral-700);
  /* Primary text — dark */
  --text-primary: var(--primitive-color-neutral-50);
  /* Secondary text — dark */
  --text-secondary: var(--primitive-color-neutral-300);
  /* Muted text — dark */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on light backgrounds — dark */
  --text-inverse: var(--primitive-color-neutral-900);
  /* Primary interactive — dark */
  --interactive-primary: var(--primitive-color-hanada-400);
  /* Primary hover — dark */
  --interactive-primary-hover: var(--primitive-color-hanada-300);
  /* Primary active — dark */
  --interactive-primary-active: var(--primitive-color-hanada-200);
  /* Default border — dark */
  --border-default: var(--primitive-color-neutral-700);
  /* Strong border — dark */
  --border-strong: var(--primitive-color-neutral-500);
  /* Error — WCAG-compliant red (dark) */
  --status-error: #EF4444;
  /* Success — WCAG-compliant green (dark) */
  --status-success: #22C55E;
  /* Warning — WCAG-compliant amber (dark) */
  --status-warning: #EAB308;
  /* Info — dark */
  --status-info: var(--primitive-color-hanada-400);
  /* Focus ring — dark */
  --focus-ring: var(--primitive-color-hanada-400);
  /* Keyboard focus — dark */
  --accessibility-focus-visible: var(--primitive-color-hanada-400);
}
`;
export const tailwindCss = `@import "tailwindcss";

@theme {
  /* --- Colors --- */
  /* Hanada (縹) 50 */
  --color-hanada-50: #F1F2F4;
  /* Hanada (縹) 100 */
  --color-hanada-100: #E2E5E9;
  /* Hanada (縹) 200 */
  --color-hanada-200: #B7CBE1;
  /* Hanada (縹) 300 */
  --color-hanada-300: #93B0D2;
  /* Hanada (縹) 400 */
  --color-hanada-400: #6F96C3;
  /* Hanada (縹) 500 */
  --color-hanada-500: #2D4A6C;
  /* Hanada (縹) 600 */
  --color-hanada-600: #21374F;
  /* Hanada (縹) 700 */
  --color-hanada-700: #171E26;
  /* Hanada (縹) 800 */
  --color-hanada-800: #0D1216;
  /* Hanada (縹) 900 */
  --color-hanada-900: #080A0D;
  /* Sakura-nezumi (桜鼠) 50 */
  --color-sakura-nezumi-50: #F3F2F2;
  /* Sakura-nezumi (桜鼠) 100 */
  --color-sakura-nezumi-100: #E7E5E4;
  /* Sakura-nezumi (桜鼠) 200 */
  --color-sakura-nezumi-200: #D2C8C6;
  /* Sakura-nezumi (桜鼠) 300 */
  --color-sakura-nezumi-300: #BCADA9;
  /* Sakura-nezumi (桜鼠) 400 */
  --color-sakura-nezumi-400: #A5918D;
  /* Sakura-nezumi (桜鼠) 500 */
  --color-sakura-nezumi-500: #B5A4A1;
  /* Sakura-nezumi (桜鼠) 600 */
  --color-sakura-nezumi-600: #A38F8A;
  /* Sakura-nezumi (桜鼠) 700 */
  --color-sakura-nezumi-700: #8C736E;
  /* Sakura-nezumi (桜鼠) 800 */
  --color-sakura-nezumi-800: #6F5C58;
  /* Sakura-nezumi (桜鼠) 900 */
  --color-sakura-nezumi-900: #534441;
  /* Wasurenagusa-iro (勿忘草色) 50 */
  --color-wasurenagusa-iro-50: #F1F3F4;
  /* Wasurenagusa-iro (勿忘草色) 100 */
  --color-wasurenagusa-iro-100: #E2E6E9;
  /* Wasurenagusa-iro (勿忘草色) 200 */
  --color-wasurenagusa-iro-200: #B6D0E2;
  /* Wasurenagusa-iro (勿忘草色) 300 */
  --color-wasurenagusa-iro-300: #91B8D4;
  /* Wasurenagusa-iro (勿忘草色) 400 */
  --color-wasurenagusa-iro-400: #6CA0C6;
  /* Wasurenagusa-iro (勿忘草色) 500 */
  --color-wasurenagusa-iro-500: #7BAACC;
  /* Wasurenagusa-iro (勿忘草色) 600 */
  --color-wasurenagusa-iro-600: #5D97C0;
  /* Wasurenagusa-iro (勿忘草色) 700 */
  --color-wasurenagusa-iro-700: #427EA9;
  /* Wasurenagusa-iro (勿忘草色) 800 */
  --color-wasurenagusa-iro-800: #336384;
  /* Wasurenagusa-iro (勿忘草色) 900 */
  --color-wasurenagusa-iro-900: #25475F;
  /* Kitsune-iro (狐色) 50 */
  --color-kitsune-iro-50: #F4F3F1;
  /* Kitsune-iro (狐色) 100 */
  --color-kitsune-iro-100: #E9E7E2;
  /* Kitsune-iro (狐色) 200 */
  --color-kitsune-iro-200: #E2D4B6;
  /* Kitsune-iro (狐色) 300 */
  --color-kitsune-iro-300: #D4BF91;
  /* Kitsune-iro (狐色) 400 */
  --color-kitsune-iro-400: #C6A96C;
  /* Kitsune-iro (狐色) 500 */
  --color-kitsune-iro-500: #C6A96C;
  /* Kitsune-iro (狐色) 600 */
  --color-kitsune-iro-600: #BA984F;
  /* Kitsune-iro (狐色) 700 */
  --color-kitsune-iro-700: #9A7C3C;
  /* Kitsune-iro (狐色) 800 */
  --color-kitsune-iro-800: #765F2E;
  /* Kitsune-iro (狐色) 900 */
  --color-kitsune-iro-900: #51411F;
  /* Enji (臙脂) 50 */
  --color-enji-50: #F4F0F1;
  /* Enji (臙脂) 100 */
  --color-enji-100: #E9E2E3;
  /* Enji (臙脂) 200 */
  --color-enji-200: #E3B5BA;
  /* Enji (臙脂) 300 */
  --color-enji-300: #D59098;
  /* Enji (臙脂) 400 */
  --color-enji-400: #C76B76;
  /* Enji (臙脂) 500 */
  --color-enji-500: #9B3B46;
  /* Enji (臙脂) 600 */
  --color-enji-600: #7E3039;
  /* Enji (臙脂) 700 */
  --color-enji-700: #592228;
  /* Enji (臙脂) 800 */
  --color-enji-800: #2D1A1C;
  /* Enji (臙脂) 900 */
  --color-enji-900: #0D0708;
  /* Rikyuu-nezumi (利休鼠) 50 */
  --color-rikyuu-nezumi-50: #F2F2F2;
  /* Rikyuu-nezumi (利休鼠) 100 */
  --color-rikyuu-nezumi-100: #E6E6E5;
  /* Rikyuu-nezumi (利休鼠) 200 */
  --color-rikyuu-nezumi-200: #CDCECA;
  /* Rikyuu-nezumi (利休鼠) 300 */
  --color-rikyuu-nezumi-300: #B4B6AF;
  /* Rikyuu-nezumi (利休鼠) 400 */
  --color-rikyuu-nezumi-400: #9A9D95;
  /* Rikyuu-nezumi (利休鼠) 500 */
  --color-rikyuu-nezumi-500: #797D73;
  /* Rikyuu-nezumi (利休鼠) 600 */
  --color-rikyuu-nezumi-600: #65675F;
  /* Rikyuu-nezumi (利休鼠) 700 */
  --color-rikyuu-nezumi-700: #4B4D47;
  /* Rikyuu-nezumi (利休鼠) 800 */
  --color-rikyuu-nezumi-800: #31322F;
  /* Rikyuu-nezumi (利休鼠) 900 */
  --color-rikyuu-nezumi-900: #171716;
  /* Shironeri (白練) 50 */
  --color-shironeri-50: #F4F3F0;
  /* Shironeri (白練) 100 */
  --color-shironeri-100: #E9E7E2;
  /* Shironeri (白練) 200 */
  --color-shironeri-200: #E5D6B3;
  /* Shironeri (白練) 300 */
  --color-shironeri-300: #D8C18D;
  /* Shironeri (白練) 400 */
  --color-shironeri-400: #CBAD67;
  /* Shironeri (白練) 500 */
  --color-shironeri-500: #EBE9E5;
  /* Shironeri (白練) 600 */
  --color-shironeri-600: #E9DCBE;
  /* Shironeri (白練) 700 */
  --color-shironeri-700: #DCC898;
  /* Shironeri (白練) 800 */
  --color-shironeri-800: #CFB372;
  /* Shironeri (白練) 900 */
  --color-shironeri-900: #C29F4C;
  /* Neutral 50 */
  --color-neutral-50: #F7F7F8;
  /* Neutral 100 */
  --color-neutral-100: #EFF0F0;
  /* Neutral 200 */
  --color-neutral-200: #DFE0E2;
  /* Neutral 300 */
  --color-neutral-300: #C5C7C9;
  /* Neutral 400 */
  --color-neutral-400: #9A9EA2;
  /* Neutral 500 */
  --color-neutral-500: #71757A;
  /* Neutral 600 */
  --color-neutral-600: #585C5F;
  /* Neutral 700 */
  --color-neutral-700: #404245;
  /* Neutral 800 */
  --color-neutral-800: #27292A;
  /* Neutral 900 */
  --color-neutral-900: #141415;
  /* Accent 50 */
  --color-accent-50: #F3F4F1;
  /* Accent 100 */
  --color-accent-100: #E7E9E2;
  /* Accent 200 */
  --color-accent-200: #D7E1B7;
  /* Accent 300 */
  --color-accent-300: #C3D293;
  /* Accent 400 */
  --color-accent-400: #AFC36F;
  /* Accent 500 */
  --color-accent-500: #5D6C2D;
  /* Accent 600 */
  --color-accent-600: #444F21;
  /* Accent 700 */
  --color-accent-700: #232617;
  /* Accent 800 */
  --color-accent-800: #14160D;
  /* Accent 900 */
  --color-accent-900: #0C0D08;

  /* --- Spacing (8px grid) --- */
  /* Spacing 0 (0px) */
  --spacing-0: 0px;
  /* Spacing 1 (4px) */
  --spacing-1: 4px;
  /* Spacing 2 (8px) */
  --spacing-2: 8px;
  /* Spacing 3 (12px) */
  --spacing-3: 12px;
  /* Spacing 4 (16px) */
  --spacing-4: 16px;
  /* Spacing 5 (20px) */
  --spacing-5: 20px;
  /* Spacing 6 (24px) */
  --spacing-6: 24px;
  /* Spacing 8 (32px) */
  --spacing-8: 32px;
  /* Spacing 10 (40px) */
  --spacing-10: 40px;
  /* Spacing 12 (48px) */
  --spacing-12: 48px;
  /* Spacing 16 (64px) */
  --spacing-16: 64px;
  /* Spacing 20 (80px) */
  --spacing-20: 80px;
  /* Spacing 0.5 (2px) */
  --spacing-0-5: 2px;
  /* Spacing 1.5 (6px) */
  --spacing-1-5: 6px;

  /* --- Font Families --- */
  /* Heading font family */
  --font-heading: "Noto Serif JP", "Noto Serif", Georgia, serif;
  /* Body font family */
  --font-body: "Noto Serif JP", "Noto Serif", Georgia, serif;
  /* Monospace font family */
  --font-mono: "JetBrains Mono", "Fira Code", monospace;

  /* --- Font Sizes --- */
  /* Font size xs */
  --text-xs: 0.75rem;
  /* Font size sm */
  --text-sm: 0.875rem;
  /* Font size base */
  --text-base: 1rem;
  /* Font size lg */
  --text-lg: 1.125rem;
  /* Font size xl */
  --text-xl: 1.25rem;
  /* Font size 2xl */
  --text-2xl: 1.5rem;
  /* Font size 3xl */
  --text-3xl: 1.875rem;
  /* Font size 4xl */
  --text-4xl: 2.25rem;

  /* --- Border Radius --- */
  /* Border radius none */
  --radius-none: 0px;
  /* Border radius sm */
  --radius-sm: 2px;
  /* Border radius md */
  --radius-md: 4px;
  /* Border radius lg */
  --radius-lg: 6px;
  /* Border radius xl */
  --radius-xl: 8px;
  /* Border radius full */
  --radius-full: 9999px;

}

/* Primitive aliases + light mode semantic tokens */
:root {
  /* --primitive-color-* aliases → @theme --color-* (for semantic var() resolution) */
  --primitive-color-hanada-50: var(--color-hanada-50);
  --primitive-color-hanada-100: var(--color-hanada-100);
  --primitive-color-hanada-200: var(--color-hanada-200);
  --primitive-color-hanada-300: var(--color-hanada-300);
  --primitive-color-hanada-400: var(--color-hanada-400);
  --primitive-color-hanada-500: var(--color-hanada-500);
  --primitive-color-hanada-600: var(--color-hanada-600);
  --primitive-color-hanada-700: var(--color-hanada-700);
  --primitive-color-hanada-800: var(--color-hanada-800);
  --primitive-color-hanada-900: var(--color-hanada-900);
  --primitive-color-sakura-nezumi-50: var(--color-sakura-nezumi-50);
  --primitive-color-sakura-nezumi-100: var(--color-sakura-nezumi-100);
  --primitive-color-sakura-nezumi-200: var(--color-sakura-nezumi-200);
  --primitive-color-sakura-nezumi-300: var(--color-sakura-nezumi-300);
  --primitive-color-sakura-nezumi-400: var(--color-sakura-nezumi-400);
  --primitive-color-sakura-nezumi-500: var(--color-sakura-nezumi-500);
  --primitive-color-sakura-nezumi-600: var(--color-sakura-nezumi-600);
  --primitive-color-sakura-nezumi-700: var(--color-sakura-nezumi-700);
  --primitive-color-sakura-nezumi-800: var(--color-sakura-nezumi-800);
  --primitive-color-sakura-nezumi-900: var(--color-sakura-nezumi-900);
  --primitive-color-wasurenagusa-iro-50: var(--color-wasurenagusa-iro-50);
  --primitive-color-wasurenagusa-iro-100: var(--color-wasurenagusa-iro-100);
  --primitive-color-wasurenagusa-iro-200: var(--color-wasurenagusa-iro-200);
  --primitive-color-wasurenagusa-iro-300: var(--color-wasurenagusa-iro-300);
  --primitive-color-wasurenagusa-iro-400: var(--color-wasurenagusa-iro-400);
  --primitive-color-wasurenagusa-iro-500: var(--color-wasurenagusa-iro-500);
  --primitive-color-wasurenagusa-iro-600: var(--color-wasurenagusa-iro-600);
  --primitive-color-wasurenagusa-iro-700: var(--color-wasurenagusa-iro-700);
  --primitive-color-wasurenagusa-iro-800: var(--color-wasurenagusa-iro-800);
  --primitive-color-wasurenagusa-iro-900: var(--color-wasurenagusa-iro-900);
  --primitive-color-kitsune-iro-50: var(--color-kitsune-iro-50);
  --primitive-color-kitsune-iro-100: var(--color-kitsune-iro-100);
  --primitive-color-kitsune-iro-200: var(--color-kitsune-iro-200);
  --primitive-color-kitsune-iro-300: var(--color-kitsune-iro-300);
  --primitive-color-kitsune-iro-400: var(--color-kitsune-iro-400);
  --primitive-color-kitsune-iro-500: var(--color-kitsune-iro-500);
  --primitive-color-kitsune-iro-600: var(--color-kitsune-iro-600);
  --primitive-color-kitsune-iro-700: var(--color-kitsune-iro-700);
  --primitive-color-kitsune-iro-800: var(--color-kitsune-iro-800);
  --primitive-color-kitsune-iro-900: var(--color-kitsune-iro-900);
  --primitive-color-enji-50: var(--color-enji-50);
  --primitive-color-enji-100: var(--color-enji-100);
  --primitive-color-enji-200: var(--color-enji-200);
  --primitive-color-enji-300: var(--color-enji-300);
  --primitive-color-enji-400: var(--color-enji-400);
  --primitive-color-enji-500: var(--color-enji-500);
  --primitive-color-enji-600: var(--color-enji-600);
  --primitive-color-enji-700: var(--color-enji-700);
  --primitive-color-enji-800: var(--color-enji-800);
  --primitive-color-enji-900: var(--color-enji-900);
  --primitive-color-rikyuu-nezumi-50: var(--color-rikyuu-nezumi-50);
  --primitive-color-rikyuu-nezumi-100: var(--color-rikyuu-nezumi-100);
  --primitive-color-rikyuu-nezumi-200: var(--color-rikyuu-nezumi-200);
  --primitive-color-rikyuu-nezumi-300: var(--color-rikyuu-nezumi-300);
  --primitive-color-rikyuu-nezumi-400: var(--color-rikyuu-nezumi-400);
  --primitive-color-rikyuu-nezumi-500: var(--color-rikyuu-nezumi-500);
  --primitive-color-rikyuu-nezumi-600: var(--color-rikyuu-nezumi-600);
  --primitive-color-rikyuu-nezumi-700: var(--color-rikyuu-nezumi-700);
  --primitive-color-rikyuu-nezumi-800: var(--color-rikyuu-nezumi-800);
  --primitive-color-rikyuu-nezumi-900: var(--color-rikyuu-nezumi-900);
  --primitive-color-shironeri-50: var(--color-shironeri-50);
  --primitive-color-shironeri-100: var(--color-shironeri-100);
  --primitive-color-shironeri-200: var(--color-shironeri-200);
  --primitive-color-shironeri-300: var(--color-shironeri-300);
  --primitive-color-shironeri-400: var(--color-shironeri-400);
  --primitive-color-shironeri-500: var(--color-shironeri-500);
  --primitive-color-shironeri-600: var(--color-shironeri-600);
  --primitive-color-shironeri-700: var(--color-shironeri-700);
  --primitive-color-shironeri-800: var(--color-shironeri-800);
  --primitive-color-shironeri-900: var(--color-shironeri-900);
  --primitive-color-neutral-50: var(--color-neutral-50);
  --primitive-color-neutral-100: var(--color-neutral-100);
  --primitive-color-neutral-200: var(--color-neutral-200);
  --primitive-color-neutral-300: var(--color-neutral-300);
  --primitive-color-neutral-400: var(--color-neutral-400);
  --primitive-color-neutral-500: var(--color-neutral-500);
  --primitive-color-neutral-600: var(--color-neutral-600);
  --primitive-color-neutral-700: var(--color-neutral-700);
  --primitive-color-neutral-800: var(--color-neutral-800);
  --primitive-color-neutral-900: var(--color-neutral-900);
  --primitive-color-accent-50: var(--color-accent-50);
  --primitive-color-accent-100: var(--color-accent-100);
  --primitive-color-accent-200: var(--color-accent-200);
  --primitive-color-accent-300: var(--color-accent-300);
  --primitive-color-accent-400: var(--color-accent-400);
  --primitive-color-accent-500: var(--color-accent-500);
  --primitive-color-accent-600: var(--color-accent-600);
  --primitive-color-accent-700: var(--color-accent-700);
  --primitive-color-accent-800: var(--color-accent-800);
  --primitive-color-accent-900: var(--color-accent-900);

  /* Semantic tokens */
  /* Page background */
  --background-canvas: var(--primitive-color-neutral-50);
  /* Card/surface background */
  --background-surface: #FFFFFF;
  /* Muted background */
  --background-muted: var(--primitive-color-neutral-100);
  /* Primary text */
  --text-primary: var(--primitive-color-neutral-900);
  /* Secondary text */
  --text-secondary: var(--primitive-color-neutral-600);
  /* Muted/disabled text */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on dark backgrounds */
  --text-inverse: var(--primitive-color-neutral-50);
  /* Primary interactive (buttons, links) */
  --interactive-primary: var(--primitive-color-hanada-500);
  /* Primary interactive hover */
  --interactive-primary-hover: var(--primitive-color-hanada-600);
  /* Primary interactive active */
  --interactive-primary-active: var(--primitive-color-hanada-700);
  /* Default border */
  --border-default: var(--primitive-color-neutral-200);
  /* Strong border */
  --border-strong: var(--primitive-color-neutral-400);
  /* Error — WCAG-compliant red */
  --status-error: #DC2626;
  /* Success — WCAG-compliant green */
  --status-success: #16A34A;
  /* Warning — WCAG-compliant amber */
  --status-warning: #CA8A04;
  /* Info status */
  --status-info: var(--primitive-color-hanada-500);
  /* Focus ring color */
  --focus-ring: var(--primitive-color-hanada-500);
  /* Keyboard focus indicator */
  --accessibility-focus-visible: var(--primitive-color-hanada-500);
}

/* Dark mode semantic tokens */
[data-theme="dark"] {
  /* Page background — dark */
  --background-canvas: var(--primitive-color-neutral-900);
  /* Card/surface — dark */
  --background-surface: var(--primitive-color-neutral-800);
  /* Muted background — dark */
  --background-muted: var(--primitive-color-neutral-700);
  /* Primary text — dark */
  --text-primary: var(--primitive-color-neutral-50);
  /* Secondary text — dark */
  --text-secondary: var(--primitive-color-neutral-300);
  /* Muted text — dark */
  --text-muted: var(--primitive-color-neutral-500);
  /* Text on light backgrounds — dark */
  --text-inverse: var(--primitive-color-neutral-900);
  /* Primary interactive — dark */
  --interactive-primary: var(--primitive-color-hanada-400);
  /* Primary hover — dark */
  --interactive-primary-hover: var(--primitive-color-hanada-300);
  /* Primary active — dark */
  --interactive-primary-active: var(--primitive-color-hanada-200);
  /* Default border — dark */
  --border-default: var(--primitive-color-neutral-700);
  /* Strong border — dark */
  --border-strong: var(--primitive-color-neutral-500);
  /* Error — WCAG-compliant red (dark) */
  --status-error: #EF4444;
  /* Success — WCAG-compliant green (dark) */
  --status-success: #22C55E;
  /* Warning — WCAG-compliant amber (dark) */
  --status-warning: #EAB308;
  /* Info — dark */
  --status-info: var(--primitive-color-hanada-400);
  /* Focus ring — dark */
  --focus-ring: var(--primitive-color-hanada-400);
  /* Keyboard focus — dark */
  --accessibility-focus-visible: var(--primitive-color-hanada-400);
}
`;
