/**
 * Generate static theme assets (tokens.json, tokens.css, tailwind.css, meta.json)
 *
 * Run: pnpm generate (from root) or tsx scripts/generate-themes.ts
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { buildFoundation } from '@syncupsuite/foundations';
import { nihonTraditionalData, swissInternationalData } from '@syncupsuite/foundations';
import { transformToTailwindV4, transformToCSS } from '@syncupsuite/transformers';
import { validateSchema, validateCompleteness, PERF_BUDGETS } from '@syncupsuite/tokens';

const __dirname = dirname(fileURLToPath(import.meta.url));
const themesDir = join(__dirname, '..', 'packages', 'themes', 'src');

const foundations = [
  { data: nihonTraditionalData, dir: 'nihon-traditional' },
  { data: swissInternationalData, dir: 'swiss-international' },
];

let hasErrors = false;

for (const { data, dir } of foundations) {
  console.log(`\nGenerating: ${dir}`);

  const { tokens, meta } = buildFoundation(data);

  // Validate
  const schemaResult = validateSchema(tokens as Record<string, unknown>);
  const completenessResult = validateCompleteness(tokens as Record<string, unknown>);

  meta.validation = {
    schema: schemaResult.valid,
    contrast: null, // not yet computed — see ADR-005
    completeness: completenessResult.valid,
  };

  if (!schemaResult.valid) {
    console.error(`  Schema errors:`, schemaResult.errors);
    hasErrors = true;
  }
  if (!completenessResult.valid) {
    console.error(`  Completeness errors:`, completenessResult.errors);
    hasErrors = true;
  }

  // Generate CSS outputs
  const css = transformToCSS(tokens);
  const tailwindCss = transformToTailwindV4(tokens);

  // Enforce performance budgets
  const cssGzipped = gzipSync(Buffer.from(css)).length;
  const propertyCount = (css.match(/^\s*--[\w-]+:/gm) ?? []).length;
  if (cssGzipped > PERF_BUDGETS.maxCssGzipped) {
    console.error(`  BUDGET: tokens.css gzipped ${cssGzipped}B > ${PERF_BUDGETS.maxCssGzipped}B`);
    hasErrors = true;
  }
  if (propertyCount > PERF_BUDGETS.maxProperties) {
    console.error(`  BUDGET: ${propertyCount} properties > ${PERF_BUDGETS.maxProperties}`);
    hasErrors = true;
  }

  // Write files
  const outDir = join(themesDir, dir);
  mkdirSync(outDir, { recursive: true });

  writeFileSync(join(outDir, 'tokens.json'), JSON.stringify(tokens, null, 2));
  writeFileSync(join(outDir, 'tokens.css'), css);
  writeFileSync(join(outDir, 'tailwind.css'), tailwindCss);
  writeFileSync(join(outDir, 'meta.json'), JSON.stringify(meta, null, 2));

  // Write embedded CSS module for programmatic access (avoids runtime computation)
  const escapedCss = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
  const escapedTailwind = tailwindCss.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
  writeFileSync(join(outDir, '_css.ts'), `// Auto-generated by scripts/generate-themes.ts — do not edit\nexport const css = \`${escapedCss}\`;\nexport const tailwindCss = \`${escapedTailwind}\`;\n`);

  console.log(`  tokens.json: ${JSON.stringify(tokens).length} bytes`);
  console.log(`  tokens.css: ${css.length} bytes raw, ${cssGzipped}B gzipped (budget: ${PERF_BUDGETS.maxCssGzipped}B)`);
  console.log(`  tailwind.css: ${tailwindCss.length} bytes`);
  console.log(`  properties: ${propertyCount} (budget: ${PERF_BUDGETS.maxProperties})`);
  console.log(`  schema: ${schemaResult.valid ? 'PASS' : 'FAIL'}`);
  console.log(`  completeness: ${completenessResult.valid ? 'PASS' : 'FAIL'}`);
}

if (hasErrors) {
  console.error('\nGeneration completed with validation errors.');
  process.exit(1);
}

console.log('\nDone.');
