// Auto-generated by scripts/generate-themes.ts — do not edit
import type { FoundationData } from './engine';

import nihonTraditionalData_ from '../data/nihon-traditional.json';
import swissInternationalData_ from '../data/swiss-international.json';

export const nihonTraditionalData = nihonTraditionalData_ as unknown as FoundationData;
export const swissInternationalData = swissInternationalData_ as unknown as FoundationData;

/** All registered foundations — used by the generator and theme browser (Phase 2/3) */
export const ALL_FOUNDATIONS: FoundationData[] = [nihonTraditionalData, swissInternationalData];
