// Foundation engine
export { buildFoundation } from './engine';
export type { FoundationData, BuildResult } from './engine';

// Color utilities
export { hexToHsl, hslToHex, generateLightnessScale, generateNeutrals, getHue } from './color';
export type { HSL } from './color';

// Harmony
export { generateHarmonyAccents } from './harmony';

// Typography
export { getFontStacks, hueToTypographyCategory, TYPE_SCALE, WEIGHT_SCALE, LINE_HEIGHT_SCALE } from './typography';

// Foundation data — auto-generated by scripts/generate-themes.ts
// Add new themes by dropping a JSON file in packages/foundations/data/ and running pnpm generate
export * from './data';
